<?php

namespace Database\Seeders;

use App\Models\Course;
use App\Models\Lesson;
use App\Models\Module;
use Illuminate\Database\Seeder;

class AuthenticLoksewaQuestionsSeeder extends Seeder
{
    public function run(): void
    {
        $this->seedAllCurriculaWithAuthenticQuestions();
    }

    private function seedAllCurriculaWithAuthenticQuestions(): void
    {
        $curricula = [
            'kharidar-tayari' => [
                'samanya-gyan-general-knowledge-1' => [
                    'Physical Geography of Nepal' => $this->getNepalGeographyQuestions(),
                    'Geography of World' => $this->getWorldGeographyQuestions(),
                    'General Information of Universe' => $this->getUniverseQuestions(),
                    'History of Nepal' => $this->getNepalHistoryQuestions(),
                    'History of World' => $this->getWorldHistoryQuestions(),
                ],
                'iq' => [
                    'Analogy' => $this->getAnalogyQuestions(),
                    'Classification' => $this->getClassificationQuestions(),
                    'Number Series' => $this->getNumberSeriesQuestions(),
                    'Letter Series' => $this->getLetterSeriesQuestions(),
                    'Coding-Decoding' => $this->getCodingDecodingQuestions(),
                ],
                'karyalaya-byawasthapan-office-management-1' => [
                    'Office Management' => $this->getOfficeManagementQuestions(),
                ],
            ],
            'nayab-subba-tayari' => [
                'nasu-general-knowledge' => [
                    'Universe and Basics' => $this->getUniverseQuestions(),
                    'Geography of World' => $this->getWorldGeographyQuestions(),
                    'Geography of Nepal' => $this->getNepalGeographyQuestions(),
                    'History of World' => $this->getWorldHistoryQuestions(),
                    'History of Nepal' => $this->getNepalHistoryQuestions(),
                ],
                'nasu-gmat' => [
                    'Verbal Reasoning' => $this->getAnalogyQuestions(),
                    'Quantitative Reasoning' => $this->getNumberSeriesQuestions(),
                    'Non-Verbal Reasoning' => $this->getClassificationQuestions(),
                ],
                'nasu-cs-psm' => [
                    'Geographical, Social and Economic Condition of Nepal' => $this->getNepalSocioEconomicQuestions(),
                    'Constitutional System and Government' => $this->getConstitutionQuestions(),
                    'Public Service Operation and Management' => $this->getPublicAdministrationQuestions(),
                ],
                'service-group-related' => [
                    'Office Operations and Organizational Behavior' => $this->getOfficeManagementQuestions(),
                    'Administration and Management' => $this->getPublicAdministrationQuestions(),
                    'Legal Provisions Related to Public Service Management' => $this->getCivilServiceLawQuestions(),
                ],
            ],
            'section-officer-tayari' => [
                'officer-gk-aat' => [
                    'Geography & Environmental Dynamics of Nepal & World' => $this->getNepalGeographyQuestions(),
                    'History, Culture & Constitutional Development of Nepal' => $this->getNepalHistoryQuestions(),
                    'International Affairs, UN, SAARC & Global Diplomacy' => $this->getWorldHistoryQuestions(),
                    'Administrative Aptitude Test (AAT): Verbal & Numerical Reasoning' => $this->getAnalogyQuestions(),
                ],
                'officer-shasan-pranali' => [
                    'State, Constitutionalism & Rule of Law in Nepal' => $this->getConstitutionQuestions(),
                    'New Public Management Concepts & Public Policy' => $this->getPublicAdministrationQuestions(),
                ],
                'officer-contemporary-issues' => [
                    'Macroeconomics, Public Finance & Fiscal Federalism in Nepal' => $this->getNepalSocioEconomicQuestions(),
                ],
                'officer-service-administration' => [
                    'Civil Service Act, Code of Conduct & Administrative Law' => $this->getCivilServiceLawQuestions(),
                ],
            ],
        ];

        foreach ($curricula as $courseSlug => $modules) {
            $course = Course::where('slug', $courseSlug)->first();
            if (! $course) {
                continue;
            }

            foreach ($modules as $moduleSlug => $lessons) {
                $module = Module::where('course_id', $course->id)
                    ->where(function ($q) use ($moduleSlug) {
                        $q->where('slug', $moduleSlug)->orWhere('slug', 'like', "%{$moduleSlug}%");
                    })
                    ->first();

                if (! $module) {
                    continue;
                }

                foreach ($lessons as $lessonTitle => $rawQuestions) {
                    $lesson = Lesson::where('module_id', $module->id)
                        ->where(function ($q) use ($lessonTitle) {
                            $q->where('title', $lessonTitle)
                                ->orWhere('title', 'like', "%{$lessonTitle}%");
                        })
                        ->first();

                    if ($lesson) {
                        $formattedQuestions = [];
                        foreach ($rawQuestions as $q) {
                            $opts = [
                                $q['option_0'] ?? ($q['options'][0] ?? ''),
                                $q['option_1'] ?? ($q['options'][1] ?? ''),
                                $q['option_2'] ?? ($q['options'][2] ?? ''),
                                $q['option_3'] ?? ($q['options'][3] ?? ''),
                            ];
                            $formattedQuestions[] = [
                                'question' => $q['question'] ?? ($q['q'] ?? ''),
                                'options' => $opts,
                                'option_0' => $opts[0],
                                'option_1' => $opts[1],
                                'option_2' => $opts[2],
                                'option_3' => $opts[3],
                                'answer' => (int) ($q['answer'] ?? ($q['a'] ?? 0)),
                                'hint' => $q['hint'] ?? ($q['h'] ?? ''),
                                'explanation' => $q['explanation'] ?? ($q['e'] ?? ''),
                            ];
                        }
                        $lesson->quiz_questions = $formattedQuestions;
                        $lesson->save();
                    }
                }
            }
        }
    }

    // =========================================================================
    // CLEAN, PURE ENGLISH LOKSEWA PSC QUESTION BANKS (NO OPTION LEAKS)
    // =========================================================================

    public function getNepalGeographyQuestions(): array
    {
        return [
            [
                'question' => 'Which is the highest mountain peak in the world located in Nepal?',
                'option_0' => 'Mount K2',
                'option_1' => 'Mount Everest',
                'option_2' => 'Kangchenjunga',
                'option_3' => 'Lhotse',
                'answer' => 1,
                'hint' => 'Known locally as Sagarmatha and in Tibetan as Chomolungma.',
                'explanation' => 'Mount Everest (Sagarmatha) is the highest peak in the world at 8848.86 meters, situated in the Mahalangur range of Solukhumbu district.',
            ],
            [
                'question' => 'Which river of Nepal is historically known in India as the "Sorrow of Bihar"?',
                'option_0' => 'Gandaki River',
                'option_1' => 'Karnali River',
                'option_2' => 'Koshi River',
                'option_3' => 'Mahakali River',
                'answer' => 2,
                'hint' => 'It frequently changes its course and causes severe monsoon flooding in northern Bihar, India.',
                'explanation' => 'The Koshi River is known as the "Sorrow of Bihar" because of annual catastrophic flooding and silt deposition caused by shifts in its meandering channel.',
            ],
            [
                'question' => 'What is the longest river in Nepal within Nepalese territorial borders?',
                'option_0' => 'Koshi River',
                'option_1' => 'Gandaki River',
                'option_2' => 'Karnali River',
                'option_3' => 'Trishuli River',
                'answer' => 2,
                'hint' => 'Originates from the Mansarovar basin in Tibet and measures 507 km within Nepal.',
                'explanation' => 'Karnali is the longest river in Nepal, measuring 507 km within Nepalese territory before flowing into India as the Ghaghara.',
            ],
            [
                'question' => 'Which is the deepest river in Nepal with the highest water discharge capacity?',
                'option_0' => 'Karnali River',
                'option_1' => 'Gandaki River',
                'option_2' => 'Koshi River',
                'option_3' => 'Bheri River',
                'answer' => 1,
                'hint' => 'Formed by seven major tributaries including Kali Gandaki, Trishuli, and Marsyangdi.',
                'explanation' => 'Gandaki (Narayani) is the deepest river in Nepal with deep gorges carved by the Kali Gandaki between Annapurna and Dhaulagiri.',
            ],
            [
                'question' => 'Which is the largest lake in Nepal by surface area?',
                'option_0' => 'Shey Phoksundo Lake',
                'option_1' => 'Fewa Lake',
                'option_2' => 'Rara Lake',
                'option_3' => 'Tilicho Lake',
                'answer' => 2,
                'hint' => 'Located in Mugu District at an altitude of 2,990 meters, praised as the Queen of Lakes.',
                'explanation' => 'Rara Lake in Mugu district is the largest freshwater lake in Nepal with a surface area of 10.8 sq km.',
            ],
            [
                'question' => 'Which is the deepest lake in Nepal?',
                'option_0' => 'Rara Lake',
                'option_1' => 'Shey Phoksundo Lake',
                'option_2' => 'Gosaikunda Lake',
                'option_3' => 'Begnas Lake',
                'answer' => 1,
                'hint' => 'An oligotrophic alpine lake situated in Dolpa district at 3,611 m altitude, famous for its turquoise blue water.',
                'explanation' => 'Shey Phoksundo Lake in Dolpa is the deepest lake in Nepal with a maximum depth of approximately 145 meters.',
            ],
            [
                'question' => 'Nepal Standard Time is determined based on which meridian passing through Gaurishankar Himal?',
                'option_0' => '80 degrees 15 minutes East Longitude',
                'option_1' => '84 degrees 00 minutes East Longitude',
                'option_2' => '86 degrees 15 minutes East Longitude',
                'option_3' => '88 degrees 00 minutes East Longitude',
                'answer' => 2,
                'hint' => 'Introduced on Baisakh 1, 2042 BS, making Nepal 5 hours and 45 minutes ahead of GMT.',
                'explanation' => 'Nepal Standard Time is based on the 86°15\' East longitude meridian intersecting Mount Gaurishankar (7,134 m), exactly GMT +5:45.',
            ],
            [
                'question' => 'Which district of Nepal is known as the district across the Himalayas receiving the lowest average annual rainfall?',
                'option_0' => 'Mustang',
                'option_1' => 'Solukhumbu',
                'option_2' => 'Sindhupalchok',
                'option_3' => 'Ramechhap',
                'answer' => 0,
                'hint' => 'Lies in the rain-shadow area north of the Annapurna and Dhaulagiri mountain ranges.',
                'explanation' => 'Mustang lies in the trans-Himalayan rain-shadow zone and receives the lowest annual rainfall in Nepal (approx. <250 mm/year).',
            ],
            [
                'question' => 'Which place in Nepal records the highest average annual rainfall?',
                'option_0' => 'Dhangadhi',
                'option_1' => 'Lumle',
                'option_2' => 'Biratnagar',
                'option_3' => 'Janakpur',
                'answer' => 1,
                'hint' => 'Located near Pokhara valley south of the Annapurna mountain barrier.',
                'explanation' => 'Lumle in Kaski district receives the highest annual rainfall in Nepal, often exceeding 5,000 mm annually (Cherrapunji of Nepal).',
            ],
            [
                'question' => 'Which was the first National Park established in Nepal?',
                'option_0' => 'Sagarmatha National Park',
                'option_1' => 'Chitwan National Park',
                'option_2' => 'Bardia National Park',
                'option_3' => 'Langtang National Park',
                'answer' => 1,
                'hint' => 'Famous habitat of the One-horned Rhinoceros and Royal Bengal Tiger in the inner Terai.',
                'explanation' => 'Chitwan National Park was established in 1973 AD (2030 BS) as Nepal’s first national park and designated a UNESCO World Heritage Site in 1984.',
            ],
        ];
    }

    public function getNepalHistoryQuestions(): array
    {
        return [
            [
                'question' => 'Who was the first Prime Minister (Mukhtiyar) of unified Nepal?',
                'option_0' => 'Jung Bahadur Rana',
                'option_1' => 'Bhimsen Thapa',
                'option_2' => 'Damodar Pande',
                'option_3' => 'Ranganath Poudel',
                'answer' => 1,
                'hint' => 'Served as Mukhtiyar from 1806 to 1837 AD and built the iconic Dharahara tower.',
                'explanation' => 'Bhimsen Thapa was the first Prime Minister (Mukhtiyar) of Nepal, serving from 1806 to 1837 AD during the reigns of King Girvan Yuddha and King Rajendra.',
            ],
            [
                'question' => 'Who was the first King of the ancient Kirat Dynasty in Nepal according to historical chronicles?',
                'option_0' => 'King Mandev',
                'option_1' => 'King Yalambar',
                'option_2' => 'King Gasti',
                'option_3' => 'King Nimish',
                'answer' => 1,
                'hint' => 'Defeated the Abhir/Mahispal dynasty to establish Kirati rule in the Kathmandu valley.',
                'explanation' => 'King Yalambar was the founder and first king of the Kirat dynasty in Nepal, ruling from Shankhamul/Gokarna.',
            ],
            [
                'question' => 'Which Licchavi King issued the first historical inscribed copper coins (Manaank) in Nepal?',
                'option_0' => 'King Amshuverma',
                'option_1' => 'King Mandev I',
                'option_2' => 'King Gunakamadev',
                'option_3' => 'King Shivadev',
                'answer' => 1,
                'hint' => 'Installed the earliest dated stone pillar inscription at Changu Narayan temple in 464 AD.',
                'explanation' => 'King Mandev I (464-505 AD) is the first authenticated historical king of Nepal who minted Manaank coins and erected the Changu Narayan inscription.',
            ],
            [
                'question' => 'The Sugauli Treaty between Nepal and the British East India Company was ratified in which year?',
                'option_0' => '1814 AD',
                'option_1' => '1816 AD',
                'option_2' => '1846 AD',
                'option_3' => '1857 AD',
                'answer' => 1,
                'hint' => 'Concluded the Anglo-Nepalese War (1814–1816) fixing the Mechi and Mahakali boundary rivers.',
                'explanation' => 'The Sugauli Treaty was signed in December 1815 and officially ratified on 4 March 1816, establishing the modern borders of Nepal.',
            ],
            [
                'question' => 'The 104-year Rana autocratic rule in Nepal began following which historical massacre in Kathmandu?',
                'option_0' => 'Bhandarkhal Massacre',
                'option_1' => 'Kot Massacre',
                'option_2' => 'Alau Massacre',
                'option_3' => '38 Saal Massacre',
                'answer' => 1,
                'hint' => 'Occurred at the royal armory courtyard in Kathmandu on Ashwin 2, 1903 BS.',
                'explanation' => 'The Kot Massacre occurred on 14 September 1846 (1903 Ashwin 2 BS), eliminating major noble courtiers and elevating Jung Bahadur Rana to power.',
            ],
            [
                'question' => 'Who established the first modern educational institution of Nepal, Durbar High School?',
                'option_0' => 'Prithvi Narayan Shah',
                'option_1' => 'Jung Bahadur Rana',
                'option_2' => 'Bir Shumsher',
                'option_3' => 'Dev Shumsher',
                'answer' => 1,
                'hint' => 'Established in 1910 BS following his historic diplomatic tour to Great Britain and France.',
                'explanation' => 'Jung Bahadur Rana founded Durbar High School inside the royal palace in 1910 BS (1853 AD) upon returning from Europe.',
            ],
            [
                'question' => 'Which King of Gorkha initiated the Great Unification Campaign of Nepal?',
                'option_0' => 'King Dravya Shah',
                'option_1' => 'King Prithvi Narayan Shah',
                'option_2' => 'King Pratap Singh Shah',
                'option_3' => 'King Bahadur Shah',
                'answer' => 1,
                'hint' => 'Conquered Nuwakot in 1801 BS and later unified Kathmandu, Patan, and Bhaktapur into a single nation.',
                'explanation' => 'King Prithvi Narayan Shah of Gorkha began the unification of Nepal by annexing Nuwakot in 1744 AD and establishing Kathmandu as the capital in 1769 AD.',
            ],
            [
                'question' => 'On which historic date was the Rana regime overthrown and Democracy declared in Nepal?',
                'option_0' => 'Falgun 7, 2007 BS',
                'option_1' => 'Chaitra 1, 2015 BS',
                'option_2' => 'Chaitra 26, 2046 BS',
                'option_3' => 'Jestha 15, 2065 BS',
                'answer' => 0,
                'hint' => 'King Tribhuvan announced the end of Rana rule over state radio; celebrated as National Democracy Day.',
                'explanation' => 'Democracy was declared in Nepal on 7th Falgun 2007 BS (18 February 1951) by King Tribhuvan after the successful tripartite revolution.',
            ],
            [
                'question' => 'Who was the first elected Prime Minister of Nepal following the general election of 2015 BS?',
                'option_0' => 'Matrika Prasad Koirala',
                'option_1' => 'Bishweshwar Prasad Koirala',
                'option_2' => 'Tanka Prasad Acharya',
                'option_3' => 'Kirti Nidhi Bista',
                'answer' => 1,
                'hint' => 'Leader of the Nepali Congress party that won a two-thirds majority in 2015 BS.',
                'explanation' => 'B.P. Koirala became the first democratically elected Prime Minister of Nepal on 13 Jestha 2016 BS (1959 AD).',
            ],
            [
                'question' => 'The Constitution of Nepal currently in force was promulgated by the Constituent Assembly on which date?',
                'option_0' => 'Mangsir 4, 2070 BS',
                'option_1' => 'Ashwin 3, 2072 BS',
                'option_2' => 'Magh 1, 2074 BS',
                'option_3' => 'Jestha 15, 2065 BS',
                'answer' => 1,
                'hint' => 'Celebrated annually across Nepal as National Constitution Day.',
                'explanation' => 'The historic federal democratic Constitution of Nepal was promulgated by the second Constituent Assembly on 3rd Ashwin 2072 BS (20 September 2015).',
            ],
        ];
    }

    public function getWorldGeographyQuestions(): array
    {
        return [
            [
                'question' => 'Which is the largest continent in the world by both surface area and total population?',
                'option_0' => 'Africa',
                'option_1' => 'Asia',
                'option_2' => 'North America',
                'option_3' => 'Europe',
                'answer' => 1,
                'hint' => 'Covers nearly 30% of Earth’s land area and is home to about 60% of the world’s population.',
                'explanation' => 'Asia is the largest and most populous continent, spanning over 44.5 million square kilometers.',
            ],
            [
                'question' => 'Which is the longest river in the world?',
                'option_0' => 'Amazon River',
                'option_1' => 'Nile River',
                'option_2' => 'Yangtze River',
                'option_3' => 'Mississippi River',
                'answer' => 1,
                'hint' => 'Flows northward through eleven countries in northeastern Africa into the Mediterranean Sea.',
                'explanation' => 'The Nile River in Africa is the longest river in the world with an estimated length of 6,650 km.',
            ],
            [
                'question' => 'Which is the largest and deepest ocean on Earth?',
                'option_0' => 'Atlantic Ocean',
                'option_1' => 'Pacific Ocean',
                'option_2' => 'Indian Ocean',
                'option_3' => 'Arctic Ocean',
                'answer' => 1,
                'hint' => 'Covers more than 30% of the Earth’s surface, larger than all land masses combined.',
                'explanation' => 'The Pacific Ocean is the largest and deepest ocean basin, containing the deepest oceanic point on Earth (Mariana Trench).',
            ],
            [
                'question' => 'What is the deepest trench in the world oceans located in the western Pacific Ocean?',
                'option_0' => 'Java Trench',
                'option_1' => 'Mariana Trench',
                'option_2' => 'Puerto Rico Trench',
                'option_3' => 'Sunda Trench',
                'answer' => 1,
                'hint' => 'Its lowest section, Challenger Deep, descends nearly 11 kilometers below sea level.',
                'explanation' => 'The Mariana Trench (Challenger Deep) is the deepest oceanic trench on Earth with a depth of approximately 11,034 meters.',
            ],
            [
                'question' => 'Which is the largest hot desert in the world?',
                'option_0' => 'Gobi Desert',
                'option_1' => 'Sahara Desert',
                'option_2' => 'Kalahari Desert',
                'option_3' => 'Thar Desert',
                'answer' => 1,
                'hint' => 'Spans over 9 million square kilometers across North Africa.',
                'explanation' => 'The Sahara Desert in North Africa is the world’s largest subtropical hot desert, covering roughly the size of the United States.',
            ],
            [
                'question' => 'Which is the world largest freshwater lake by surface area?',
                'option_0' => 'Lake Baikal',
                'option_1' => 'Lake Superior',
                'option_2' => 'Lake Victoria',
                'option_3' => 'Caspian Sea',
                'answer' => 1,
                'hint' => 'One of the Great Lakes shared between the United States and Canada.',
                'explanation' => 'Lake Superior is the world’s largest freshwater lake by surface area (approx. 82,100 sq km).',
            ],
            [
                'question' => 'Which is the deepest freshwater lake in the world located in Siberia, Russia?',
                'option_0' => 'Lake Tanganyika',
                'option_1' => 'Lake Baikal',
                'option_2' => 'Lake Malawi',
                'option_3' => 'Lake Huron',
                'answer' => 1,
                'hint' => 'Contains 20% of the world’s unfrozen surface fresh water.',
                'explanation' => 'Lake Baikal in Russia is the deepest lake in the world with a maximum depth of 1,642 meters (5,387 feet).',
            ],
            [
                'question' => 'Which strait separates Asia from North America connecting the Arctic Ocean with the Bering Sea?',
                'option_0' => 'Strait of Gibraltar',
                'option_1' => 'Bering Strait',
                'option_2' => 'Strait of Malacca',
                'option_3' => 'Bosphorus Strait',
                'answer' => 1,
                'hint' => 'Lies between Cape Dezhnev in Russia and Cape Prince of Wales in Alaska.',
                'explanation' => 'The Bering Strait connects the Chukchi Sea (Arctic Ocean) with the Bering Sea (Pacific Ocean), separating Russia from Alaska.',
            ],
            [
                'question' => 'Which is the longest continental mountain range in the world?',
                'option_0' => 'Himalayas',
                'option_1' => 'Andes Mountain Range',
                'option_2' => 'Rocky Mountains',
                'option_3' => 'Alps',
                'answer' => 1,
                'hint' => 'Runs along the entire western coast of South America through seven countries.',
                'explanation' => 'The Andes is the longest continental mountain range in the world, extending about 7,000 km along western South America.',
            ],
            [
                'question' => 'Which country in the world is known as the Land of the Midnight Sun?',
                'option_0' => 'Japan',
                'option_1' => 'Norway',
                'option_2' => 'Canada',
                'option_3' => 'New Zealand',
                'answer' => 1,
                'hint' => 'During summer months north of the Arctic Circle, the sun never sets below the horizon.',
                'explanation' => 'Norway is called the Land of the Midnight Sun because northern regions experience continuous daylight during summer.',
            ],
        ];
    }

    public function getUniverseQuestions(): array
    {
        return [
            [
                'question' => 'Which is the closest star to the planet Earth?',
                'option_0' => 'Proxima Centauri',
                'option_1' => 'The Sun',
                'option_2' => 'Sirius',
                'option_3' => 'Alpha Centauri',
                'answer' => 1,
                'hint' => 'The center of our Solar System located approximately 149.6 million km from Earth.',
                'explanation' => 'The Sun is the closest star to Earth; light from the Sun takes approximately 8 minutes and 20 seconds to reach Earth.',
            ],
            [
                'question' => 'Which planet in the Solar System is closest to the Sun?',
                'option_0' => 'Venus',
                'option_1' => 'Mercury',
                'option_2' => 'Mars',
                'option_3' => 'Earth',
                'answer' => 1,
                'hint' => 'The smallest planet in the solar system with an orbital period of just 88 Earth days.',
                'explanation' => 'Mercury is the innermost and smallest planet in our Solar System, orbiting closest to the Sun.',
            ],
            [
                'question' => 'Which planet is known as both the Morning Star and Evening Star and is the hottest planet in the Solar System?',
                'option_0' => 'Mercury',
                'option_1' => 'Venus',
                'option_2' => 'Mars',
                'option_3' => 'Jupiter',
                'answer' => 1,
                'hint' => 'Dense carbon dioxide atmosphere creates an extreme runaway greenhouse effect.',
                'explanation' => 'Venus is the brightest natural object in night skies after the Moon and the hottest planet (~465°C) due to dense CO2 atmosphere.',
            ],
            [
                'question' => 'Which planet in the Solar System is known as the Red Planet?',
                'option_0' => 'Mercury',
                'option_1' => 'Mars',
                'option_2' => 'Jupiter',
                'option_3' => 'Saturn',
                'answer' => 1,
                'hint' => 'Its surface contains abundant iron oxide giving it a reddish appearance.',
                'explanation' => 'Mars is called the Red Planet because widespread iron oxide on its surface imparts a distinct reddish tint.',
            ],
            [
                'question' => 'Which is the largest planet in our Solar System?',
                'option_0' => 'Saturn',
                'option_1' => 'Jupiter',
                'option_2' => 'Neptune',
                'option_3' => 'Uranus',
                'answer' => 1,
                'hint' => 'A gas giant with the famous Great Red Spot storm, having a mass more than double all other planets combined.',
                'explanation' => 'Jupiter is the largest planet in the Solar System with a diameter of ~142,984 km and over 90 known moons.',
            ],
            [
                'question' => 'Which planet in our Solar System is famously surrounded by prominent, bright planetary rings made of ice and dust?',
                'option_0' => 'Jupiter',
                'option_1' => 'Saturn',
                'option_2' => 'Uranus',
                'option_3' => 'Neptune',
                'answer' => 1,
                'hint' => 'The second largest planet in the Solar System, with Titan as its largest moon.',
                'explanation' => 'Saturn is renowned for its spectacular and complex ring system composed predominantly of water ice and rocky debris.',
            ],
            [
                'question' => 'What is the name of the barred spiral galaxy containing our Solar System?',
                'option_0' => 'Andromeda Galaxy',
                'option_1' => 'Milky Way Galaxy',
                'option_2' => 'Triangulum Galaxy',
                'option_3' => 'Whirlpool Galaxy',
                'answer' => 1,
                'hint' => 'A spiral galaxy containing 100 to 400 billion stars.',
                'explanation' => 'Our Solar System is located in the Orion Arm of the Milky Way galaxy.',
            ],
            [
                'question' => 'What is the speed of light in a vacuum?',
                'option_0' => '150,000 km/s',
                'option_1' => '300,000 km/s',
                'option_2' => '500,000 km/s',
                'option_3' => '3,000 km/s',
                'answer' => 1,
                'hint' => 'Fundamental physical constant denoted by the letter c.',
                'explanation' => 'Light travels at approximately 299,792 km/s (~300,000 km/second) in a vacuum.',
            ],
            [
                'question' => 'Which celestial object was reclassified from a major planet to a Dwarf Planet by the IAU in 2006?',
                'option_0' => 'Ceres',
                'option_1' => 'Pluto',
                'option_2' => 'Eris',
                'option_3' => 'Makemake',
                'answer' => 1,
                'hint' => 'Discovered in 1930 by Clyde Tombaugh in the Kuiper Belt.',
                'explanation' => 'Pluto was reclassified as a dwarf planet by the IAU in August 2006 because it had not cleared the neighborhood around its orbit.',
            ],
            [
                'question' => 'What was the world first artificial satellite launched into Earth orbit by the Soviet Union in 1957?',
                'option_0' => 'Explorer 1',
                'option_1' => 'Sputnik 1',
                'option_2' => 'Vostok 1',
                'option_3' => 'Apollo 11',
                'answer' => 1,
                'hint' => 'Marked the beginning of the human Space Age on October 4, 1957.',
                'explanation' => 'Sputnik 1 was the first artificial satellite placed in orbit by the USSR on 4 October 1957, initiating the global Space Race.',
            ],
        ];
    }

    public function getWorldHistoryQuestions(): array
    {
        return [
            [
                'question' => 'The French Revolution began in which year with the storming of the Bastille prison?',
                'option_0' => '1776 AD',
                'option_1' => '1789 AD',
                'option_2' => '1804 AD',
                'option_3' => '1815 AD',
                'answer' => 1,
                'hint' => 'Adopted the famous motto: Liberty, Equality, Fraternity.',
                'explanation' => 'The French Revolution commenced on 14 July 1789 with the storming of the Bastille in Paris, overturning absolute feudal monarchy.',
            ],
            [
                'question' => 'In which country did the Industrial Revolution first begin in the mid-18th century?',
                'option_0' => 'France',
                'option_1' => 'Great Britain',
                'option_2' => 'Germany',
                'option_3' => 'United States',
                'answer' => 1,
                'hint' => 'Pioneered through mechanized textile manufacturing, steam engines, and coal mining.',
                'explanation' => 'The Industrial Revolution originated in Great Britain around 1760 due to inventions like James Watt’s steam engine and access to capital and coal.',
            ],
            [
                'question' => 'The American Declaration of Independence from British rule was officially adopted on which date?',
                'option_0' => 'July 4, 1776 AD',
                'option_1' => 'August 15, 1783 AD',
                'option_2' => 'January 1, 1789 AD',
                'option_3' => 'December 25, 1775 AD',
                'answer' => 0,
                'hint' => 'Drafted by Thomas Jefferson and signed in Philadelphia; celebrated as US Independence Day.',
                'explanation' => 'The 13 American colonies declared independence from Great Britain on July 4, 1776 in Philadelphia.',
            ],
            [
                'question' => 'What was the duration of the First World War?',
                'option_0' => '1912 to 1916 AD',
                'option_1' => '1914 to 1918 AD',
                'option_2' => '1939 to 1945 AD',
                'option_3' => '1905 to 1911 AD',
                'answer' => 1,
                'hint' => 'Triggered by the assassination of Archduke Franz Ferdinand of Austria in Sarajevo in June 1914.',
                'explanation' => 'World War I lasted from 28 July 1914 to 11 November 1918, ending with the signing of the Treaty of Versailles in 1919.',
            ],
            [
                'question' => 'World War II began in September 1939 with Germany invasion of which country?',
                'option_0' => 'France',
                'option_1' => 'Poland',
                'option_2' => 'Soviet Union',
                'option_3' => 'Austria',
                'answer' => 1,
                'hint' => 'Led Great Britain and France to declare war on Nazi Germany two days later.',
                'explanation' => 'World War II commenced on September 1, 1939 when Adolf Hitler’s Nazi Germany launched a blitzkrieg invasion of Poland.',
            ],
            [
                'question' => 'The Russian Bolshevik Revolution in 1917 was led by which revolutionary leader?',
                'option_0' => 'Joseph Stalin',
                'option_1' => 'Vladimir Lenin',
                'option_2' => 'Leon Trotsky',
                'option_3' => 'Karl Marx',
                'answer' => 1,
                'hint' => 'Overthrew Tsar Nicholas II and the provisional government to establish the Soviet Union.',
                'explanation' => 'Vladimir Lenin led the Bolsheviks during the October Revolution in November 1917, establishing the world’s first socialist state.',
            ],
            [
                'question' => 'On which two Japanese cities did the United States drop atomic bombs in August 1945?',
                'option_0' => 'Tokyo and Kyoto',
                'option_1' => 'Hiroshima and Nagasaki',
                'option_2' => 'Osaka and Yokohama',
                'option_3' => 'Sapporo and Kobe',
                'answer' => 1,
                'hint' => 'Little Boy was dropped on August 6 and Fat Man on August 9, 1945.',
                'explanation' => 'The US detonated atomic bombs over Hiroshima on 6 August 1945 and Nagasaki on 9 August 1945, leading to Japan’s surrender.',
            ],
            [
                'question' => 'In which year was the United Nations officially founded in San Francisco?',
                'option_0' => '1919 AD',
                'option_1' => '1945 AD',
                'option_2' => '1948 AD',
                'option_3' => '1955 AD',
                'answer' => 1,
                'hint' => 'Charter signed by 51 original member states on October 24, 1945.',
                'explanation' => 'The United Nations was officially established on 24 October 1945 when the UN Charter was ratified by the permanent Security Council members and majority signatories.',
            ],
            [
                'question' => 'The historic fall of the Berlin Wall occurred in which year?',
                'option_0' => '1985 AD',
                'option_1' => '1989 AD',
                'option_2' => '1991 AD',
                'option_3' => '1995 AD',
                'answer' => 1,
                'hint' => 'Paved the way for German reunification in 1990 and the dissolution of the Soviet Union.',
                'explanation' => 'The Berlin Wall fell on 9 November 1989, uniting East and West Germany and marking the symbolic end of the Cold War.',
            ],
            [
                'question' => 'The Magna Carta, the foundational charter limiting royal power and establishing rule of law, was signed in England in:',
                'option_0' => '1066 AD',
                'option_1' => '1215 AD',
                'option_2' => '1492 AD',
                'option_3' => '1688 AD',
                'answer' => 1,
                'hint' => 'Granted by King John of England at Runnymede.',
                'explanation' => 'King John of England granted the Magna Carta on 15 June 1215, establishing the legal principle that everyone, including the monarch, is subject to the law.',
            ],
        ];
    }

    public function getOfficeManagementQuestions(): array
    {
        return [
            [
                'question' => 'What is the primary purpose of the Registration (Darta) ledger in public offices?',
                'option_0' => 'To prepare annual employee salary payroll',
                'option_1' => 'To systematically record incoming official letters and documents entering the office',
                'option_2' => 'To record outgoing letters dispatched to other agencies',
                'option_3' => 'To record daily staff attendance',
                'answer' => 1,
                'hint' => 'The initial registration ledger where all incoming official correspondence is logged.',
                'explanation' => 'Darta is the official ledger used to systematically record all incoming letters, notices, and documents received by an office.',
            ],
            [
                'question' => 'What is the Dispatch (Chalani) book used for in public office administration?',
                'option_0' => 'Recording incoming letters from citizens',
                'option_1' => 'Systematically recording and dispatching outgoing official correspondence to external agencies',
                'option_2' => 'Calculating staff pension benefits',
                'option_3' => 'Storing obsolete records in archive',
                'answer' => 1,
                'hint' => 'Assigns unique dispatch numbers and date to letters sent out from the office.',
                'explanation' => 'Chalani is the register where all outgoing letters, circulars, and orders sent from the office are numbered and documented.',
            ],
            [
                'question' => 'What does an Administrative Note / Minute (Tippani) represent in government decision-making in Nepal?',
                'option_0' => 'A casual informal comment',
                'option_1' => 'A structured administrative file note presenting facts, legal provisions, and recommendations for higher approval',
                'option_2' => 'An annual auditing ledger',
                'option_3' => 'A commercial purchase order invoice',
                'answer' => 1,
                'hint' => 'The formal written channel through which official policy and executive decisions are routed upwards for hierarchical approval.',
                'explanation' => 'Tippani is an administrative memo prepared on a case file that details background, rules, precedents, and proposed decisions for authorized sanction.',
            ],
            [
                'question' => 'Which filing system arranges documents based on geographic locations such as Provinces, Districts, and Municipalities?',
                'option_0' => 'Alphabetical Filing',
                'option_1' => 'Geographical Filing',
                'option_2' => 'Chronological Filing',
                'option_3' => 'Numerical Filing',
                'answer' => 1,
                'hint' => 'Organizes files by territory or administrative regions.',
                'explanation' => 'Geographical filing groups and stores records according to territorial jurisdictions, regions, or branch locations.',
            ],
            [
                'question' => 'In public administration, what is a Citizen Charter?',
                'option_0' => 'A political party election manifesto',
                'option_1' => 'A public declaration displayed at government offices stating services offered, required documents, timeframe, fees, and grievance redressal officers',
                'option_2' => 'A tax assessment booklet',
                'option_3' => 'An internal employee disciplinary manual',
                'answer' => 1,
                'hint' => 'Guarantees service delivery standards and public accountability to service seekers.',
                'explanation' => 'A Citizen Charter is a visible institutional commitment outlining the nature of services, turnaround times, fees, officer in charge, and compensation procedures.',
            ],
            [
                'question' => 'Under Nepal Good Governance Act 2064, within what timeframe must a public body deliver administrative services when all documents are complete?',
                'option_0' => 'Immediately or within the timeframe specified in the Citizen Charter',
                'option_1' => 'Within 6 months',
                'option_2' => 'Whenever staff are free',
                'option_3' => 'Within 1 year',
                'answer' => 0,
                'hint' => 'Services must be delivered promptly without causing unnecessary delays to citizens.',
                'explanation' => 'Section 16 of the Good Governance Act 2064 mandates that every public agency must provide services immediately or strictly within the timeline published in its Citizen Charter.',
            ],
            [
                'question' => 'What is the purpose of Record Management / Archiving in public offices?',
                'option_0' => 'Destroying all old files immediately',
                'option_1' => 'Systematically classifying, preserving valuable records, and disposing of obsolete files per statutory rules',
                'option_2' => 'Restricting information from public access permanently',
                'option_3' => 'Increasing office paperwork costs',
                'answer' => 1,
                'hint' => 'Governed by the Record Preservation and Disposal Rules in Nepal.',
                'explanation' => 'Record management ensures systematic retention of historical, legal, and operational documents while safely disposing of time-expired records.',
            ],
            [
                'question' => 'What is a Circular (Paripatra) in administrative correspondence?',
                'option_0' => 'A personal letter to a friend',
                'option_1' => 'A single official directive or notice sent simultaneously to multiple subordinate offices for uniform implementation',
                'option_2' => 'A personal leave application',
                'option_3' => 'A tender invitation notice published in a newspaper',
                'answer' => 1,
                'hint' => 'Sent from higher headquarters to all branch or field offices.',
                'explanation' => 'A circular (Paripatra) is an official communication addressing multiple subordinates or departments regarding administrative directives or operational rules.',
            ],
            [
                'question' => 'What is the primary role of the Information Officer appointed in every public agency under the Right to Information Act 2064?',
                'option_0' => 'Drafting annual financial budgets',
                'option_1' => 'Receiving citizen RTI requests, collecting information from departments, and disseminating it within statutory deadlines',
                'option_2' => 'Handling court litigation only',
                'option_3' => 'Inspecting physical office furniture',
                'answer' => 1,
                'hint' => 'Mandated by Section 6 of the RTI Act 2064 to uphold institutional transparency.',
                'explanation' => 'The Information Officer is the statutory liaison responsible for processing public information requests and proactively disclosing public agency data.',
            ],
            [
                'question' => 'Which of the following is considered an essential element of modern electronic office management (e-Office)?',
                'option_0' => 'Complete reliance on manual paper registers',
                'option_1' => 'Paperless digital workflows, electronic signatures, automated file routing, and biometric attendance',
                'option_2' => 'Eliminating internet connectivity',
                'option_3' => 'Restricting computer access to senior executives only',
                'answer' => 1,
                'hint' => 'Improves administrative speed, transparency, and traceability.',
                'explanation' => 'Digital office systems (e-Office) streamline government processes through electronic document handling, computerized dispatch, and audit trails.',
            ],
        ];
    }

    public function getConstitutionQuestions(): array
    {
        return [
            [
                'question' => 'How many Parts, Articles, and Schedules are contained in the Constitution of Nepal 2072?',
                'option_0' => '25 Parts, 250 Articles, 7 Schedules',
                'option_1' => '35 Parts, 308 Articles, 9 Schedules',
                'option_2' => '30 Parts, 300 Articles, 8 Schedules',
                'option_3' => '40 Parts, 320 Articles, 10 Schedules',
                'answer' => 1,
                'hint' => 'Promulgated on Ashwin 3, 2072 BS by the Constituent Assembly.',
                'explanation' => 'The Constitution of Nepal comprises 35 Parts, 308 Articles, and 9 Schedules.',
            ],
            [
                'question' => 'Which Part of the Constitution of Nepal enshrines the 31 Fundamental Rights?',
                'option_0' => 'Part 2',
                'option_1' => 'Part 3',
                'option_2' => 'Part 4',
                'option_3' => 'Part 5',
                'answer' => 1,
                'hint' => 'Spans from Article 16 (Right to live with dignity) to Article 46 (Right to constitutional remedies).',
                'explanation' => 'Part 3 of the Constitution of Nepal provides 31 fundamental rights enforceable through the courts under Articles 46 and 133.',
            ],
            [
                'question' => 'Under Article 7 of the Constitution of Nepal, which language in Devanagari script is designated as the Official Language of government business?',
                'option_0' => 'Maithili',
                'option_1' => 'Nepali Language',
                'option_2' => 'Bhojpuri',
                'option_3' => 'English Language',
                'answer' => 1,
                'hint' => 'Written in Devanagari script; provinces may also designate additional regional languages.',
                'explanation' => 'Article 7(1) states that the Nepali language in Devanagari script shall be the official language of government business in Nepal.',
            ],
            [
                'question' => 'Who is the executive head of the Government of Nepal under the constitutional parliamentary system?',
                'option_0' => 'The President',
                'option_1' => 'The Prime Minister',
                'option_2' => 'The Chief Justice',
                'option_3' => 'The Speaker of the House',
                'answer' => 1,
                'hint' => 'Appointed under Article 76 from the party or coalition commanding a majority in the House of Representatives.',
                'explanation' => 'Under Article 75, executive power is vested in the Council of Ministers headed by the Prime Minister.',
            ],
            [
                'question' => 'How many total members are there in the federal House of Representatives of Nepal?',
                'option_0' => '205 members',
                'option_1' => '275 members',
                'option_2' => '330 members',
                'option_3' => '601 members',
                'answer' => 1,
                'hint' => '165 elected through First-Past-The-Post and 110 through Proportional Representation.',
                'explanation' => 'Article 84 establishes the 275-member House of Representatives: 165 directly elected from single-member constituencies and 110 elected proportionally.',
            ],
            [
                'question' => 'How many members constitute the National Assembly (Upper House) of Nepal?',
                'option_0' => '50 members',
                'option_1' => '59 members',
                'option_2' => '75 members',
                'option_3' => '100 members',
                'answer' => 1,
                'hint' => '56 elected from 7 provinces (8 from each province) and 3 nominated by the President.',
                'explanation' => 'Article 86 provides that the National Assembly consists of 59 members, serving as a permanent house with one-third retiring every two years.',
            ],
            [
                'question' => 'Under Article 242 of the Constitution, which constitutional body conducts examinations for selection of candidates to civil service posts?',
                'option_0' => 'Election Commission',
                'option_1' => 'Public Service Commission',
                'option_2' => 'Commission for the Investigation of Abuse of Authority',
                'option_3' => 'National Human Rights Commission',
                'answer' => 1,
                'hint' => 'The premier merit-based recruitment authority established in 2008 BS.',
                'explanation' => 'The Public Service Commission (Article 242) conducts competitive examinations for appointments to the civil service, military, police, and public state enterprises.',
            ],
            [
                'question' => 'Which schedule of the Constitution of Nepal lists the 22 Exclusive Powers of the Local Level?',
                'option_0' => 'Schedule 5',
                'option_1' => 'Schedule 8',
                'option_2' => 'Schedule 6',
                'option_3' => 'Schedule 9',
                'answer' => 1,
                'hint' => 'Includes local police, local taxes, basic education, and local health services.',
                'explanation' => 'Schedule 8 outlines the 22 exclusive legislative and executive powers of Municipalities and Rural Municipalities in Nepal.',
            ],
            [
                'question' => 'Who administers the oath of office and secrecy to the President of Nepal under Article 70?',
                'option_0' => 'The Prime Minister',
                'option_1' => 'The Chief Justice of Nepal',
                'option_2' => 'The Speaker of the House',
                'option_3' => 'The Chairman of the National Assembly',
                'answer' => 1,
                'hint' => 'The head of the judicial branch of the state.',
                'explanation' => 'Under the Constitution, the President takes the oath of office before the Chief Justice of the Supreme Court of Nepal.',
            ],
            [
                'question' => 'What is the total number of Provinces in the federal structure of Nepal?',
                'option_0' => '5 Provinces',
                'option_1' => '7 Provinces',
                'option_2' => '9 Provinces',
                'option_3' => '14 Zones',
                'answer' => 1,
                'hint' => 'Replaced the old 5 development regions and 14 zones.',
                'explanation' => 'Article 56 partitions Nepal into 7 federal provinces (Koshi, Madhesh, Bagmati, Gandaki, Lumbini, Karnali, and Sudurpashchim).',
            ],
        ];
    }

    public function getAnalogyQuestions(): array
    {
        return [
            [
                'question' => 'Kathmandu : Nepal :: New Delhi : ?',
                'option_0' => 'China',
                'option_1' => 'India',
                'option_2' => 'Pakistan',
                'option_3' => 'Bangladesh',
                'answer' => 1,
                'hint' => 'Relationship is Capital City to Country.',
                'explanation' => 'Kathmandu is the capital of Nepal; New Delhi is the capital of India.',
            ],
            [
                'question' => 'Mount Everest : Nepal :: Mount Kilimanjaro : ?',
                'option_0' => 'Kenya',
                'option_1' => 'Tanzania',
                'option_2' => 'Egypt',
                'option_3' => 'South Africa',
                'answer' => 1,
                'hint' => 'Highest peak of Africa located in this East African country.',
                'explanation' => 'Mount Everest is the highest mountain in Nepal; Mount Kilimanjaro is the highest peak in Tanzania (Africa).',
            ],
            [
                'question' => 'Thermometer : Temperature :: Barometer : ?',
                'option_0' => 'Humidity',
                'option_1' => 'Atmospheric Pressure',
                'option_2' => 'Wind Velocity',
                'option_3' => 'Earthquake Intensity',
                'answer' => 1,
                'hint' => 'Instrument to measuring quantity relationship.',
                'explanation' => 'A thermometer measures temperature; a barometer measures atmospheric pressure.',
            ],
            [
                'question' => 'Doctor : Hospital :: Teacher : ?',
                'option_0' => 'Court',
                'option_1' => 'School',
                'option_2' => 'Laboratory',
                'option_3' => 'Library',
                'answer' => 1,
                'hint' => 'Professional to workplace relationship.',
                'explanation' => 'A doctor works in a hospital; a teacher works in a school.',
            ],
            [
                'question' => 'Heart : Cardiology :: Brain : ?',
                'option_0' => 'Dermatology',
                'option_1' => 'Neurology',
                'option_2' => 'Nephrology',
                'option_3' => 'Oncology',
                'answer' => 1,
                'hint' => 'Organ to medical specialization relationship.',
                'explanation' => 'Cardiology is the study of the heart; neurology is the study of the brain and nervous system.',
            ],
            [
                'question' => 'Book : Author :: Statue : ?',
                'option_0' => 'Painter',
                'option_1' => 'Sculptor',
                'option_2' => 'Architect',
                'option_3' => 'Mason',
                'answer' => 1,
                'hint' => 'Creation to creator relationship.',
                'explanation' => 'An author writes a book; a sculptor carves a statue.',
            ],
            [
                'question' => 'Pen : Writer :: Scalpel : ?',
                'option_0' => 'Carpenter',
                'option_1' => 'Surgeon',
                'option_2' => 'Tailor',
                'option_3' => 'Sculptor',
                'answer' => 1,
                'hint' => 'Tool to professional relationship.',
                'explanation' => 'A pen is the working tool of a writer; a scalpel is the surgical tool of a surgeon.',
            ],
            [
                'question' => 'Nepal : Rupee :: Japan : ?',
                'option_0' => 'Dollar',
                'option_1' => 'Yen',
                'option_2' => 'Won',
                'option_3' => 'Yuan',
                'answer' => 1,
                'hint' => 'Country to official currency relationship.',
                'explanation' => 'Rupee is the currency of Nepal; Yen is the official currency of Japan.',
            ],
            [
                'question' => 'Fish : Gills :: Human : ?',
                'option_0' => 'Skin',
                'option_1' => 'Lungs',
                'option_2' => 'Heart',
                'option_3' => 'Trachea',
                'answer' => 1,
                'hint' => 'Organism to primary respiratory organ relationship.',
                'explanation' => 'Fish breathe through gills; human beings breathe using lungs.',
            ],
            [
                'question' => 'Ornithology : Birds :: Entomology : ?',
                'option_0' => 'Fossils',
                'option_1' => 'Insects',
                'option_2' => 'Plants',
                'option_3' => 'Fungi',
                'answer' => 1,
                'hint' => 'Branch of zoology to organism studied.',
                'explanation' => 'Ornithology is the scientific study of birds; entomology is the scientific study of insects.',
            ],
        ];
    }

    public function getClassificationQuestions(): array
    {
        return [
            [
                'question' => 'Find the odd one out among the following geographical features:',
                'option_0' => 'Mount Everest',
                'option_1' => 'Rara Lake',
                'option_2' => 'Kangchenjunga',
                'option_3' => 'Annapurna',
                'answer' => 1,
                'hint' => 'Three are mountain peaks while one is a lake.',
                'explanation' => 'Mount Everest, Kangchenjunga, and Annapurna are Himalayan mountain peaks; Rara is a lake.',
            ],
            [
                'question' => 'Which of the following is the odd one out among SAARC member nations?',
                'option_0' => 'Nepal',
                'option_1' => 'Myanmar',
                'option_2' => 'Bhutan',
                'option_3' => 'Sri Lanka',
                'answer' => 1,
                'hint' => 'Three are founding members of SAARC; one is a member of ASEAN.',
                'explanation' => 'Nepal, Bhutan, and Sri Lanka are SAARC member states; Myanmar belongs to ASEAN and is not a member of SAARC.',
            ],
            [
                'question' => 'Find the odd number out in the group: 2, 3, 5, 7, 9, 11, 13',
                'option_0' => '7',
                'option_1' => '9',
                'option_2' => '11',
                'option_3' => '13',
                'answer' => 1,
                'hint' => 'All other numbers are prime numbers except this composite number.',
                'explanation' => 'All numbers in the set are prime numbers except 9, which is a composite number divisible by 3.',
            ],
            [
                'question' => 'Find the odd one out among the following cities:',
                'option_0' => 'Kathmandu',
                'option_1' => 'Sydney',
                'option_2' => 'Tokyo',
                'option_3' => 'London',
                'answer' => 1,
                'hint' => 'Canberra is the capital of Australia, not Sydney.',
                'explanation' => 'Kathmandu, Tokyo, and London are national capitals; Sydney is a major Australian city but Canberra is the capital.',
            ],
            [
                'question' => 'Which of the following organs is the odd one out?',
                'option_0' => 'Eyes',
                'option_1' => 'Stomach',
                'option_2' => 'Ears',
                'option_3' => 'Nose',
                'answer' => 1,
                'hint' => 'Three are external sensory organs; one is an internal digestive organ.',
                'explanation' => 'Eyes, ears, and nose are sensory organs; the stomach is an internal digestive organ.',
            ],
            [
                'question' => 'Find the odd one out among computer input and output hardware devices:',
                'option_0' => 'Keyboard',
                'option_1' => 'Printer',
                'option_2' => 'Mouse',
                'option_3' => 'Scanner',
                'answer' => 1,
                'hint' => 'Three are input devices; one is an output device.',
                'explanation' => 'Keyboard, Mouse, and Scanner are input devices; Printer is an output peripheral.',
            ],
            [
                'question' => 'Find the odd one out among objects in the Solar System:',
                'option_0' => 'Earth',
                'option_1' => 'Moon',
                'option_2' => 'Mars',
                'option_3' => 'Venus',
                'answer' => 1,
                'hint' => 'Three are planets orbiting the Sun; one is a natural satellite orbiting Earth.',
                'explanation' => 'Earth, Mars, and Venus are planets; the Moon is a natural satellite.',
            ],
            [
                'question' => 'Which unit of measurement is the odd one out?',
                'option_0' => 'Kilogram',
                'option_1' => 'Kilometer',
                'option_2' => 'Gram',
                'option_3' => 'Pound',
                'answer' => 1,
                'hint' => 'Three measure mass/weight; one measures distance/length.',
                'explanation' => 'Kilogram, Gram, and Pound measure mass/weight; Kilometer measures distance.',
            ],
            [
                'question' => 'Find the odd one out among the following substances:',
                'option_0' => 'Iron',
                'option_1' => 'Diamond',
                'option_2' => 'Copper',
                'option_3' => 'Gold',
                'answer' => 1,
                'hint' => 'Three are metallic chemical elements; one is an allotrope of carbon.',
                'explanation' => 'Iron, Copper, and Gold are metallic elements; Diamond is a crystalline non-metallic allotrope of Carbon.',
            ],
            [
                'question' => 'Find the odd one out among state agencies of Nepal:',
                'option_0' => 'Public Service Commission',
                'option_1' => 'National Planning Commission',
                'option_2' => 'Election Commission',
                'option_3' => 'Commission for the Investigation of Abuse of Authority',
                'answer' => 1,
                'hint' => 'Three are constitutional bodies created directly under Parts 21-24; one is an executive advisory body.',
                'explanation' => 'PSC, Election Commission, and CIAA are constitutional bodies; the National Planning Commission is an executive advisory agency.',
            ],
        ];
    }

    public function getNumberSeriesQuestions(): array
    {
        return [
            [
                'question' => 'Find the next number in the series: 2, 4, 8, 16, 32, ?',
                'option_0' => '48',
                'option_1' => '64',
                'option_2' => '56',
                'option_3' => '72',
                'answer' => 1,
                'hint' => 'Each number is multiplied by 2.',
                'explanation' => 'Pattern: 2x2=4, 4x2=8, 8x2=16, 16x2=32, 32x2 = 64.',
            ],
            [
                'question' => 'Find the next term in the series: 3, 6, 11, 18, 27, ?',
                'option_0' => '36',
                'option_1' => '38',
                'option_2' => '40',
                'option_3' => '42',
                'answer' => 1,
                'hint' => 'Differences are successive odd numbers: +3, +5, +7, +9, +11.',
                'explanation' => 'Differences: 6-3=3, 11-6=5, 18-11=7, 27-18=9. Next difference is +11: 27 + 11 = 38.',
            ],
            [
                'question' => 'Find the missing number in the Fibonacci sequence: 1, 1, 2, 3, 5, 8, 13, ?',
                'option_0' => '18',
                'option_1' => '21',
                'option_2' => '24',
                'option_3' => '26',
                'answer' => 1,
                'hint' => 'Each term is the sum of the two preceding terms.',
                'explanation' => 'Fibonacci sequence: 1+1=2, 1+2=3, 2+3=5, 3+5=8, 5+8=13, 8+13 = 21.',
            ],
            [
                'question' => 'Find the next number in the series: 1, 4, 9, 16, 25, 36, ?',
                'option_0' => '45',
                'option_1' => '49',
                'option_2' => '54',
                'option_3' => '64',
                'answer' => 1,
                'hint' => 'Perfect squares of natural numbers: 1², 2², 3², 4², 5², 6², 7².',
                'explanation' => 'Series of squares: 1²=1, 2²=4, 3²=9, 4²=16, 5²=25, 6²=36, 7² = 49.',
            ],
            [
                'question' => 'Find the next term in the series: 1, 8, 27, 64, 125, ?',
                'option_0' => '196',
                'option_1' => '216',
                'option_2' => '225',
                'option_3' => '343',
                'answer' => 1,
                'hint' => 'Series of cubes: 1³, 2³, 3³, 4³, 5³, 6³.',
                'explanation' => '1³=1, 2³=8, 3³=27, 4³=64, 5³=125, 6³ = 216.',
            ],
            [
                'question' => 'Find the missing number: 100, 95, 85, 70, 50, ?',
                'option_0' => '30',
                'option_1' => '25',
                'option_2' => '20',
                'option_3' => '35',
                'answer' => 1,
                'hint' => 'Subtracting consecutive multiples of 5: -5, -10, -15, -20, -25.',
                'explanation' => '100-5=95, 95-10=85, 85-15=70, 70-20=50, 50-25 = 25.',
            ],
            [
                'question' => 'Find the next number in the alternating series: 2, 3, 5, 6, 8, 9, 11, ?',
                'option_0' => '13',
                'option_1' => '12',
                'option_2' => '14',
                'option_3' => '15',
                'answer' => 1,
                'hint' => 'Pattern alternates: +1, +2, +1, +2, +1, +2, +1.',
                'explanation' => '2+1=3, 3+2=5, 5+1=6, 6+2=8, 8+1=9, 9+2=11, 11+1 = 12.',
            ],
            [
                'question' => 'Find the missing term: 4, 9, 19, 39, 79, ?',
                'option_0' => '149',
                'option_1' => '159',
                'option_2' => '169',
                'option_3' => '179',
                'answer' => 1,
                'hint' => 'Multiply by 2 and add 1.',
                'explanation' => '(4x2)+1=9, (9x2)+1=19, (19x2)+1=39, (39x2)+1=79, (79x2)+1 = 159.',
            ],
            [
                'question' => 'Find the next number in the series: 120, 99, 80, 63, 48, ?',
                'option_0' => '32',
                'option_1' => '35',
                'option_2' => '38',
                'option_3' => '40',
                'answer' => 1,
                'hint' => 'Pattern: 11²-1, 10²-1, 9²-1, 8²-1, 7²-1, 6²-1.',
                'explanation' => '11²-1=120, 10²-1=99, 9²-1=80, 8²-1=63, 7²-1=48, 6²-1 = 35.',
            ],
            [
                'question' => 'Find the missing number in the series: 7, 14, 28, 56, 112, ?',
                'option_0' => '214',
                'option_1' => '224',
                'option_2' => '230',
                'option_3' => '240',
                'answer' => 1,
                'hint' => 'Doubling each number: 112 multiplied by 2.',
                'explanation' => '7x2=14, 14x2=28, 28x2=56, 56x2=112, 112x2 = 224.',
            ],
        ];
    }

    public function getLetterSeriesQuestions(): array
    {
        return [
            [
                'question' => 'Find the next letter in the series: A, C, E, G, I, ?',
                'option_0' => 'J',
                'option_1' => 'K',
                'option_2' => 'L',
                'option_3' => 'M',
                'answer' => 1,
                'hint' => 'Skipping one letter forward (+2 positions).',
                'explanation' => 'Letter positions: A(1), C(3), E(5), G(7), I(9). Next is position 11 = K.',
            ],
            [
                'question' => 'Find the next term in the series: Z, X, V, T, R, ?',
                'option_0' => 'O',
                'option_1' => 'P',
                'option_2' => 'Q',
                'option_3' => 'N',
                'answer' => 1,
                'hint' => 'Moving backwards by 2 letters (-2 positions).',
                'explanation' => 'Z(26), X(24), V(22), T(20), R(18). Next is 18 - 2 = 16 = P.',
            ],
            [
                'question' => 'Find the missing group of letters: AB, CD, EF, GH, ?',
                'option_0' => 'IK',
                'option_1' => 'IJ',
                'option_2' => 'JK',
                'option_3' => 'IL',
                'answer' => 1,
                'hint' => 'Consecutive alphabet pairs.',
                'explanation' => 'The series groups consecutive letters: AB, CD, EF, GH, IJ.',
            ],
            [
                'question' => 'Find the next letter in the series: B, D, G, K, P, ?',
                'option_0' => 'U',
                'option_1' => 'V',
                'option_2' => 'W',
                'option_3' => 'X',
                'answer' => 1,
                'hint' => 'Increments increase by 1 each step: +2, +3, +4, +5, +6.',
                'explanation' => 'B(2)+2=D(4), D(4)+3=G(7), G(7)+4=K(11), K(11)+5=P(16). Next: 16+6 = 22 = V.',
            ],
            [
                'question' => 'Find the next term in the series: AZ, BY, CX, DW, ?',
                'option_0' => 'ET',
                'option_1' => 'EV',
                'option_2' => 'FU',
                'option_3' => 'EW',
                'answer' => 1,
                'hint' => 'Pairs of opposite letters from start and end of alphabet.',
                'explanation' => 'First letter moves forward (A, B, C, D, E), second moves backward (Z, Y, X, W, V) -> EV.',
            ],
            [
                'question' => 'What is the missing term: CBA, FED, IHG, LKJ, ?',
                'option_0' => 'NML',
                'option_1' => 'ONM',
                'option_2' => 'PON',
                'option_3' => 'MLK',
                'answer' => 1,
                'hint' => 'Triplets of 3 letters written in reverse order.',
                'explanation' => 'CBA is ABC reversed, FED is DEF reversed, IHG is GHI reversed, LKJ is JKL reversed. Next is MNO reversed = ONM.',
            ],
            [
                'question' => 'Find the next letter in the series: A, D, I, P, ?',
                'option_0' => 'W',
                'option_1' => 'Y',
                'option_2' => 'X',
                'option_3' => 'Z',
                'answer' => 1,
                'hint' => 'Positions correspond to square numbers: 1², 2², 3², 4², 5².',
                'explanation' => 'Square number positions: 1²=A(1), 2²=D(4), 3²=I(9), 4²=P(16), 5²=Y(25).',
            ],
            [
                'question' => 'Find the next term in the series: KPA, LQB, MRC, NSD, ?',
                'option_0' => 'OTE',
                'option_1' => 'OTE',
                'option_2' => 'PTE',
                'option_3' => 'OTF',
                'answer' => 0,
                'hint' => 'Each letter in the triplet shifts +1 position.',
                'explanation' => 'First letters: K, L, M, N, O. Second: P, Q, R, S, T. Third: A, B, C, D, E -> OTE.',
            ],
            [
                'question' => 'Find the next letter: J, F, M, A, M, J, J, A, S, O, N, ?',
                'option_0' => 'O',
                'option_1' => 'D',
                'option_2' => 'P',
                'option_3' => 'F',
                'answer' => 1,
                'hint' => 'First letters of the 12 calendar months: January, February, March... December.',
                'explanation' => 'The series represents the first letter of each month of the year. The 12th month is December (D).',
            ],
            [
                'question' => 'Find the missing letter in the series: O, T, T, F, F, S, S, E, N, ?',
                'option_0' => 'E',
                'option_1' => 'T',
                'option_2' => 'O',
                'option_3' => 'S',
                'answer' => 1,
                'hint' => 'First letters of natural numbers: One, Two, Three, Four, Five, Six, Seven, Eight, Nine, Ten.',
                'explanation' => 'The letters represent the initial letters of English numbers 1 through 10. Number 10 is Ten, so the answer is T.',
            ],
        ];
    }

    public function getCodingDecodingQuestions(): array
    {
        return [
            [
                'question' => 'If in a certain code, "LOKSEWA" is written as "MQLTFZB", how is "NEPAL" written in that code?',
                'option_0' => 'OFQBM',
                'option_1' => 'OFQBN',
                'option_2' => 'OGQBN',
                'option_3' => 'PEQBM',
                'answer' => 0,
                'hint' => 'Each letter is shifted forward by +1 position.',
                'explanation' => 'Applying +1 forward shift to each letter: N->O, E->F, P->Q, A->B, L->M = OFQBM.',
            ],
            [
                'question' => 'If "CAT" is coded as 24, what is the numerical code value for "DOG"?',
                'option_0' => '22',
                'option_1' => '26',
                'option_2' => '28',
                'option_3' => '30',
                'answer' => 1,
                'hint' => 'Sum of the alphabetical position values of the letters: D=4, O=15, G=7.',
                'explanation' => 'D=4, O=15, G=7. Sum = 4 + 15 + 7 = 26.',
            ],
            [
                'question' => 'If "BOOK" is coded as "CPPL", how is "READ" coded in the same language?',
                'option_0' => 'SFBE',
                'option_1' => 'SEBE',
                'option_2' => 'SGBE',
                'option_3' => 'TFBE',
                'answer' => 0,
                'hint' => 'Shift each letter forward by +1 position.',
                'explanation' => 'R->S, E->F, A->B, D->E = SFBE.',
            ],
            [
                'question' => 'In a code language, if "WATER" is coded as "YCVGT", what is the code for "RIVER"?',
                'option_0' => 'TKXGT',
                'option_1' => 'SKXGT',
                'option_2' => 'TKYGT',
                'option_3' => 'UKXGT',
                'answer' => 0,
                'hint' => 'Shift each letter forward by +2 positions.',
                'explanation' => 'Each letter advances by 2 positions: R+2=T, I+2=K, V+2=X, E+2=G, R+2=T -> TKXGT.',
            ],
            [
                'question' => 'If "SUN" is coded as 54, what is the code for "MOON"?',
                'option_0' => '50',
                'option_1' => '57',
                'option_2' => '60',
                'option_3' => '62',
                'answer' => 1,
                'hint' => 'Sum of letter positions: M=13, O=15, O=15, N=14.',
                'explanation' => '13 + 15 + 15 + 14 = 57.',
            ],
            [
                'question' => 'If "PEN" is written as "QFO", how is "INK" written in that code?',
                'option_0' => 'JOL',
                'option_1' => 'KOL',
                'option_2' => 'JPM',
                'option_3' => 'INL',
                'answer' => 0,
                'hint' => 'Shift each letter forward by +1 position.',
                'explanation' => 'I->J, N->O, K->L = JOL.',
            ],
            [
                'question' => 'If in a code language, 123 means "Hot Filtered Coffee", 356 means "Very Hot Day", and 589 means "Day and Night", which digit stands for "Very"?',
                'option_0' => '3',
                'option_1' => '6',
                'option_2' => '5',
                'option_3' => '8',
                'answer' => 1,
                'hint' => 'Compare the common digits and common words across phrases.',
                'explanation' => 'Comparing sentences: 3 = Hot, 5 = Day. In "356" = "Very Hot Day", the remaining digit 6 represents "Very".',
            ],
            [
                'question' => 'If "DELHI" is coded as "EDMGJ", how is "MUMBAI" coded in that pattern?',
                'option_0' => 'NTNBZJ',
                'option_1' => 'NTNCZJ',
                'option_2' => 'NTNCBJ',
                'option_3' => 'MTNBZJ',
                'answer' => 0,
                'hint' => 'Alternating +1 and -1 shift pattern on each letter.',
                'explanation' => 'M+1=N, U-1=T, M+1=N, B-1=A/Z, A+1=B, I+1=J -> NTNBZJ.',
            ],
            [
                'question' => 'If "KTM" is written as "JSL", how is "POK" written in that code?',
                'option_0' => 'ONJ',
                'option_1' => 'QPL',
                'option_2' => 'OMJ',
                'option_3' => 'PPL',
                'answer' => 0,
                'hint' => 'Subtract 1 position (-1) from each letter.',
                'explanation' => 'P-1=O, O-1=N, K-1=J -> ONJ.',
            ],
            [
                'question' => 'If "NEPAL" is coded in reverse as "LAPEN", how is "KHARIDAR" coded in the same system?',
                'option_0' => 'RADIRAHK',
                'option_1' => 'RADIRAKH',
                'option_2' => 'RADAIRHK',
                'option_3' => 'RADIRAHM',
                'answer' => 0,
                'hint' => 'Spell the word backwards from right to left.',
                'explanation' => 'Reversing K-H-A-R-I-D-A-R yields R-A-D-I-R-A-H-K.',
            ],
        ];
    }

    public function getNepalSocioEconomicQuestions(): array
    {
        return [
            [
                'question' => 'According to the National Population and Housing Census 2078, what is the total population of Nepal?',
                'option_0' => '26,494,504',
                'option_1' => '29,164,578',
                'option_2' => '31,000,000',
                'option_3' => '28,000,000',
                'answer' => 1,
                'hint' => 'Female population accounts for 51.02% and male population 48.98%.',
                'explanation' => 'The National Census 2078 recorded Nepal’s total population at 29,164,578 with an annual population growth rate of 0.92%.',
            ],
            [
                'question' => 'What is the national literacy rate of Nepal as per the Census 2078?',
                'option_0' => '65.9%',
                'option_1' => '76.3%',
                'option_2' => '82.5%',
                'option_3' => '71.0%',
                'answer' => 1,
                'hint' => 'Male literacy stands at 83.6% and female literacy at 69.4%.',
                'explanation' => 'Census 2078 showed a total literacy rate of 76.3% (Male: 83.6%, Female: 69.4%).',
            ],
            [
                'question' => 'Which province of Nepal has the highest population as per Census 2078?',
                'option_0' => 'Koshi Province',
                'option_1' => 'Bagmati Province',
                'option_2' => 'Madhesh Province',
                'option_3' => 'Lumbini Province',
                'answer' => 1,
                'hint' => 'Home to the federal capital Kathmandu, accommodating ~20.97% of the total population.',
                'explanation' => 'Bagmati Province has the highest population (6,116,866 or 20.97%), while Karnali Province has the lowest (5.79%).',
            ],
            [
                'question' => 'What is the standard fiscal year cycle in Nepal?',
                'option_0' => 'January 1 to December 31',
                'option_1' => 'Shrawan 1 to Ashad end',
                'option_2' => 'Baisakh 1 to Chaitra end',
                'option_3' => 'April 1 to March 31',
                'answer' => 1,
                'hint' => 'Annual federal budget is constitutionally presented on Jestha 15 for the upcoming fiscal year starting Shrawan 1.',
                'explanation' => 'Nepal’s fiscal year runs from 1st Shrawan (mid-July) to the end of Ashad (mid-July of the following calendar year).',
            ],
            [
                'question' => 'On which constitutional date is the Federal Annual Budget presented by the Finance Minister to Parliament?',
                'option_0' => 'Baisakh 1 BS',
                'option_1' => 'Jestha 15 BS',
                'option_2' => 'Ashad 1 BS',
                'option_3' => 'Shrawan 1 BS',
                'answer' => 1,
                'hint' => 'Fixed by Article 119(3) of the Constitution of Nepal on Republic Day.',
                'explanation' => 'Article 119(3) constitutionally mandates the Finance Minister to present the annual revenue and expenditure estimates on 15th Jestha.',
            ],
            [
                'question' => 'Which is the largest contributor to the Gross Domestic Product (GDP) of Nepal among broad economic sectors?',
                'option_0' => 'Manufacturing Sector',
                'option_1' => 'Services Sector',
                'option_2' => 'Agriculture and Forestry Sector',
                'option_3' => 'Mining Sector',
                'answer' => 1,
                'hint' => 'Includes trade, real estate, banking, education, transport, and hospitality.',
                'explanation' => 'The services tertiary sector contributes over 60% of Nepal’s GDP, followed by agriculture (~24%) and industry (~13%).',
            ],
            [
                'question' => 'Which is the major cash crop and agricultural export product of eastern Nepal?',
                'option_0' => 'Paddy',
                'option_1' => 'Orthodox Tea and Large Cardamom',
                'option_2' => 'Wheat',
                'option_3' => 'Cotton',
                'answer' => 1,
                'hint' => 'Cultivated in high hills of Ilam, Jhapa, Panchthar, and Taplejung.',
                'explanation' => 'Orthodox tea, large cardamom (Alainchi), and ginger are major agricultural exports contributing significantly to rural income in eastern Nepal.',
            ],
            [
                'question' => 'Which highway is the longest national highway in Nepal traversing east to west?',
                'option_0' => 'Prithvi Highway',
                'option_1' => 'Mahendra Highway',
                'option_2' => 'Tribhuvan Highway',
                'option_3' => 'Mid-Hill Highway',
                'answer' => 1,
                'hint' => 'Extends from Kakarbhitta in the east to Gaddachauki in the west (1,027 km).',
                'explanation' => 'Mahendra Highway (East-West Highway) spans 1,027.67 km connecting Mechi to Mahakali across the Terai belt.',
            ],
            [
                'question' => 'Which international airport in Nepal was inaugurated on January 1, 2023 as the country third international airport?',
                'option_0' => 'Tribhuvan International Airport',
                'option_1' => 'Pokhara International Airport',
                'option_2' => 'Gautam Buddha International Airport',
                'option_3' => 'Nijgadh International Airport',
                'answer' => 1,
                'hint' => 'Located in the prime tourist city of Gandaki province.',
                'explanation' => 'Pokhara International Airport was officially inaugurated for operation on January 1, 2023.',
            ],
            [
                'question' => 'Nepal is officially targeted to graduate from Least Developed Country (LDC) category to Developing Country status by:',
                'option_0' => '2024 AD',
                'option_1' => '2026 AD',
                'option_2' => '2030 AD',
                'option_3' => '2035 AD',
                'answer' => 1,
                'hint' => 'Recommended by the UN Committee for Development Policy with a 5-year preparatory transition period.',
                'explanation' => 'Nepal is scheduled to graduate from the UN Least Developed Country (LDC) category to a Developing Country by November 2026.',
            ],
        ];
    }

    public function getPublicAdministrationQuestions(): array
    {
        return [
            [
                'question' => 'What is the classic definition of Public Administration as articulated by Woodrow Wilson in 1887?',
                'option_0' => 'A purely political election campaign tool',
                'option_1' => 'Detailed and systematic execution of public law',
                'option_2' => 'Private commercial trade management',
                'option_3' => 'A judicial criminal trial process',
                'answer' => 1,
                'hint' => 'Woodrow Wilson is celebrated as the Father of Public Administration.',
                'explanation' => 'Woodrow Wilson defined public administration as the detailed and systematic execution of public law in his seminal essay "The Study of Administration" (1887).',
            ],
            [
                'question' => 'Who coined the famous administrative management acronym POSDCORB?',
                'option_0' => 'Henri Fayol',
                'option_1' => 'Luther Gulick and Lyndall Urwick',
                'option_2' => 'Max Weber',
                'option_3' => 'Herbert Simon',
                'answer' => 1,
                'hint' => 'Planning, Organizing, Staffing, Directing, Coordinating, Reporting, and Budgeting.',
                'explanation' => 'Luther Gulick formulated POSDCORB to summarize the core executive functions of administrative management.',
            ],
            [
                'question' => 'What are the three essential pillars of the classic 3Es in public expenditure audit?',
                'option_0' => 'Equity, Environment, Emotion',
                'option_1' => 'Economy, Efficiency, and Effectiveness',
                'option_2' => 'Execution, Evaluation, Elimination',
                'option_3' => 'Electricity, Energy, Emission',
                'answer' => 1,
                'hint' => 'Evaluated by the Auditor General to ensure value for taxpayer money.',
                'explanation' => 'Value-for-money audits evaluate Economy (minimizing cost of inputs), Efficiency (maximizing output per input), and Effectiveness (achieving target outcomes).',
            ],
            [
                'question' => 'Which administrative reform concept emphasizes viewing citizens as customers and measuring government by results?',
                'option_0' => 'Traditional Bureaucracy',
                'option_1' => 'New Public Management',
                'option_2' => 'Spoils System',
                'option_3' => 'Legal Formalism',
                'answer' => 1,
                'hint' => 'Emerged in the 1980s and 1990s through Osborne and Gaebler’s Reinventing Government.',
                'explanation' => 'New Public Management incorporates market-driven practices, customer satisfaction, accountability, and output indicators into public administration.',
            ],
            [
                'question' => 'What is the primary role of the Public Accounts Committee of Parliament in Nepal?',
                'option_0' => 'Levying local property taxes',
                'option_1' => 'Examining the Annual Audit Report of the Auditor General and holding ministries accountable for fiscal irregularities',
                'option_2' => 'Drafting civil service exam questions',
                'option_3' => 'Managing foreign exchange reserves',
                'answer' => 1,
                'hint' => 'Chaired customarily by an opposition member of parliament to maintain oversight.',
                'explanation' => 'The PAC examines public accounts and the Auditor General’s report, summoning secretaries and ministers to resolve audit arrears (Beruju).',
            ],
            [
                'question' => 'Which principle of natural justice requires that No person shall be a judge in their own cause?',
                'option_0' => 'Audi Alteram Partem',
                'option_1' => 'Nemo Judex In Causa Sua',
                'option_2' => 'Ultra Vires',
                'option_3' => 'Locus Standi',
                'answer' => 1,
                'hint' => 'Ensures that decision-makers have no personal, financial, or familial bias in the subject matter.',
                'explanation' => 'Nemo Judex In Causa Sua prohibits bias and conflict of interest, ensuring that judges and administrators remain strictly neutral.',
            ],
            [
                'question' => 'In Nepal, which apex constitutional body investigates corruption and improper conduct of public post holders?',
                'option_0' => 'National Human Rights Commission',
                'option_1' => 'Commission for the Investigation of Abuse of Authority',
                'option_2' => 'Public Service Commission',
                'option_3' => 'Judicial Council',
                'answer' => 1,
                'hint' => 'Established under Part 21 (Article 238) of the Constitution of Nepal.',
                'explanation' => 'The CIAA investigates corruption offenses and prosecutes public officials before the Special Court.',
            ],
            [
                'question' => 'What does Audit Arrears (Beruju) signify in government accounting in Nepal?',
                'option_0' => 'Total budget surplus at year end',
                'option_1' => 'Transactions or expenditures executed without statutory authority, supporting documents, or in violation of financial rules',
                'option_2' => 'Foreign grant received from abroad',
                'option_3' => 'Employee tax deductions',
                'answer' => 1,
                'hint' => 'Flagged annually in the Auditor General’s report under advance arrears, unregularized spending, or misappropriation.',
                'explanation' => 'Beruju represents financial transactions executed contrary to prevailing laws, regulations, or accounting standards, requiring recovery or regularization.',
            ],
            [
                'question' => 'Under Nepal Public Procurement Act 2063, what is the default and standard method for purchasing public goods and civil works?',
                'option_0' => 'Direct sole-source purchase',
                'option_1' => 'Open Competitive Bidding',
                'option_2' => 'User committee construction without quotation',
                'option_3' => 'Secret negotiation',
                'answer' => 1,
                'hint' => 'Ensures equal opportunity, transparency, and competitive pricing for public value.',
                'explanation' => 'The Public Procurement Act 2063 mandates open competitive national or international bidding as the principal procurement method.',
            ],
            [
                'question' => 'What is the primary role of a Social Audit in public development projects?',
                'option_0' => 'Checking bank account interest rates',
                'option_1' => 'Engaging direct beneficiaries and citizens in a public forum to evaluate project expenditure, quality, and service responsiveness',
                'option_2' => 'Calculating employee income tax',
                'option_3' => 'Filing international patent applications',
                'answer' => 1,
                'hint' => 'A participatory social accountability tool practiced across local governments in Nepal.',
                'explanation' => 'Social audit brings community members and officials together to transparently review project resources, progress, and public satisfaction.',
            ],
        ];
    }

    public function getCivilServiceLawQuestions(): array
    {
        return [
            [
                'question' => 'According to the Civil Service Act 2049 of Nepal, what is the mandatory age of retirement for civil servants?',
                'option_0' => '55 years',
                'option_1' => '58 years',
                'option_2' => '60 years',
                'option_3' => '62 years',
                'answer' => 1,
                'hint' => 'Prescribed in Section 33 of the Civil Service Act 2049.',
                'explanation' => 'Section 33 of the Civil Service Act 2049 fixes the compulsory retirement age for permanent civil servants at 58 years.',
            ],
            [
                'question' => 'What is the probation period for newly appointed male and female civil servants respectively?',
                'option_0' => '1 year for both',
                'option_1' => '1 year for male, 6 months for female',
                'option_2' => '6 months for male, 1 year for female',
                'option_3' => '2 years for both',
                'answer' => 1,
                'hint' => 'Affirmative action provision under Section 10 of the Civil Service Act.',
                'explanation' => 'Section 10 provides that a female civil servant completes probation in 6 months, whereas a male civil servant requires 1 year.',
            ],
            [
                'question' => 'What percentage of vacant civil service posts are reserved for inclusive clusters in open recruitment?',
                'option_0' => '33%',
                'option_1' => '45%',
                'option_2' => '50%',
                'option_3' => '55%',
                'answer' => 1,
                'hint' => '55% is open to all citizens; the remaining 45% is allocated among inclusive categories.',
                'explanation' => 'Section 7(7) of the Civil Service Act 2049 reserves 45% of open recruitment vacancies for specified inclusive categories.',
            ],
            [
                'question' => 'Which of the following is considered an Ordinary Departmental Punishment under the Civil Service Act?',
                'option_0' => 'Dismissal from service with disqualification',
                'option_1' => 'Reprimand or withholding grade increment and promotion for up to 2 years',
                'option_2' => 'Removal from service without disqualification',
                'option_3' => 'Criminal jail sentence',
                'answer' => 1,
                'hint' => 'Special punishments involve termination; ordinary penalties involve warnings or grade/promotion withholding.',
                'explanation' => 'Section 59 categorizes Nasihat (reprimand) and withholding of promotion/grade increments as ordinary departmental punishments.',
            ],
            [
                'question' => 'Under the Civil Service Code of Conduct, civil servants are strictly prohibited from:',
                'option_0' => 'Wearing clean official uniforms',
                'option_1' => 'Participating in partisan political campaigns, strikes, or accepting unauthorized gifts',
                'option_2' => 'Attending official trainings',
                'option_3' => 'Exercising legal delegated authority',
                'answer' => 1,
                'hint' => 'Ensures political neutrality, integrity, and undivided loyalty to public duty.',
                'explanation' => 'Sections 41 to 55 mandate political neutrality, punctuality, prohibition of strikes, and non-acceptance of unauthorized gifts by civil servants.',
            ],
            [
                'question' => 'What is the minimum qualifying service period required for a civil servant to be eligible for lifelong pension in Nepal?',
                'option_0' => '10 years',
                'option_1' => '20 years',
                'option_2' => '25 years',
                'option_3' => '15 years',
                'answer' => 1,
                'hint' => 'Those retiring before 20 years receive gratuity instead of monthly pension.',
                'explanation' => 'Section 37 of the Civil Service Act specifies that civil servants who have completed 20 years or more of permanent service are entitled to monthly pension.',
            ],
            [
                'question' => 'Which body evaluates performance appraisals for civil service promotion?',
                'option_0' => 'Judicial Service Council',
                'option_1' => 'Performance Appraisal Review Committee',
                'option_2' => 'Parliamentary Committee',
                'option_3' => 'Trade Union Board',
                'answer' => 1,
                'hint' => 'Evaluated out of 40 marks annually by Supervisor, Reviewer, and Review Committee.',
                'explanation' => 'Section 24A outlines the 40-mark annual appraisal assessed by the direct supervisor (25 marks), reviewer (10 marks), and review committee (5 marks).',
            ],
            [
                'question' => 'Under Nepal Contribution-Based Pension Act 2075, what percentage of monthly salary is deducted from a civil servant basic salary for their pension fund?',
                'option_0' => '3%',
                'option_1' => '6%',
                'option_2' => '10%',
                'option_3' => '12%',
                'answer' => 1,
                'hint' => 'Matched equally with 6% contributed by the Government of Nepal (total 12%).',
                'explanation' => 'Under the Pension Fund Act 2075, 6% is deducted from the employee’s basic salary and matched with 6% from the government.',
            ],
            [
                'question' => 'How many total days of Casual Leave and Festival Leave is a permanent civil servant entitled to each year?',
                'option_0' => '6 days',
                'option_1' => '12 days in total',
                'option_2' => '18 days',
                'option_3' => '30 days',
                'answer' => 1,
                'hint' => 'Composed of 6 days of casual leave and 6 days of festive leave.',
                'explanation' => 'Rule 55 of the Civil Service Rules grants 6 days of casual leave and 6 days of festive leave, totaling 12 days annually.',
            ],
            [
                'question' => 'What is the maximum number of days of Home Leave a civil servant can accumulate for cash encashment upon retirement?',
                'option_0' => '90 days',
                'option_1' => '180 days',
                'option_2' => '240 days',
                'option_3' => '365 days',
                'answer' => 1,
                'hint' => 'Earned at the rate of 1 day for every 12 days of working service.',
                'explanation' => 'A civil servant can accumulate up to 180 days of home leave and 150 days of sick leave, encashable upon retirement.',
            ],
        ];
    }
}
