<?php

namespace App\Services;

use App\Models\Course;
use App\Models\Lesson;
use Dompdf\Dompdf;
use Dompdf\Options;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class LessonPdfGeneratorService
{
    private static bool $autoloadRegistered = false;

    public function __construct()
    {
        self::ensureAutoload();
    }

    private static function ensureAutoload(): void
    {
        if (self::$autoloadRegistered) {
            return;
        }

        $cpdfPath = base_path('vendor/dompdf/dompdf/lib/Cpdf.php');
        if (file_exists($cpdfPath) && ! class_exists('Dompdf\Cpdf', false)) {
            require_once $cpdfPath;
        }

        spl_autoload_register(function ($class) {
            $prefixes = [
                'Dompdf\\' => base_path('vendor/dompdf/dompdf/src/'),
                'FontLib\\' => base_path('vendor/dompdf/php-font-lib/src/FontLib/'),
                'Svg\\' => base_path('vendor/dompdf/php-svg-lib/src/Svg/'),
                'Sabberworm\\CSS\\' => base_path('vendor/sabberworm/php-css-parser/src/'),
                'Barryvdh\\DomPDF\\' => base_path('vendor/barryvdh/laravel-dompdf/src/'),
            ];

            foreach ($prefixes as $prefix => $baseDir) {
                $len = strlen($prefix);
                if (strncmp($prefix, $class, $len) !== 0) {
                    continue;
                }

                $relativeClass = substr($class, $len);
                $file = $baseDir.str_replace('\\', '/', $relativeClass).'.php';

                if (file_exists($file)) {
                    require_once $file;

                    return;
                }
            }
        });

        self::$autoloadRegistered = true;
    }

    /**
     * Check if a lesson already has an existing valid attached PDF.
     */
    public function hasValidPdf(Lesson $lesson): bool
    {
        $path = $lesson->attachment_path;
        if (empty($path)) {
            return false;
        }

        if (Str::startsWith($path, ['http://', 'https://'])) {
            return true;
        }

        if (Storage::disk('public')->exists($path)) {
            return true;
        }

        if (file_exists(public_path($path))) {
            return true;
        }

        if (file_exists(public_path('storage/'.$path))) {
            return true;
        }

        return false;
    }

    /**
     * Generate pure theoretical PDFs for all targeted lessons (those generated with lesson_note_* or without PDFs).
     * Preserves all original historical PDFs.
     */
    public function generateMissingLessonPdfs(bool $forceRegenerateGenerated = true): array
    {
        $storageDir1 = public_path('storage/lessons/pdfs');
        $storageDir2 = storage_path('app/public/lessons/pdfs');

        if (! is_dir($storageDir1)) {
            mkdir($storageDir1, 0755, true);
        }
        if (! is_dir($storageDir2)) {
            mkdir($storageDir2, 0755, true);
        }

        $allLessons = Lesson::with(['chapter.module.course', 'module.course'])->orderBy('id')->get();
        $generated = [];
        $skipped = [];

        foreach ($allLessons as $lesson) {
            $isCustomGenerated = Str::startsWith($lesson->attachment_path ?? '', 'lessons/pdfs/lesson_note_');

            // If lesson has an original PDF (not generated by us), keep it completely untouched!
            if (! $isCustomGenerated && $this->hasValidPdf($lesson)) {
                $skipped[] = [
                    'id' => $lesson->id,
                    'title' => $lesson->title,
                    'path' => $lesson->attachment_path,
                ];
                continue;
            }

            // If it already has our generated PDF and we're not forcing regeneration, skip
            if (! $forceRegenerateGenerated && $this->hasValidPdf($lesson)) {
                continue;
            }

            $course = $lesson->course;
            $module = $lesson->module ?? $lesson->chapter?->module;

            $filename = 'lesson_note_'.$lesson->id.'_'.Str::slug(substr($lesson->title, 0, 30)).'.pdf';
            $relativeAttachmentPath = 'lessons/pdfs/'.$filename;
            $fullPath1 = $storageDir1.'/'.$filename;
            $fullPath2 = $storageDir2.'/'.$filename;

            $html = $this->buildPureTheoreticalHtml($lesson, $course, $module);
            $this->renderPdfToFile($html, $fullPath1);

            // Mirror to storage/app/public/lessons/pdfs/
            File::copy($fullPath1, $fullPath2);

            $lesson->update([
                'attachment_path' => $relativeAttachmentPath,
            ]);

            $generated[] = [
                'id' => $lesson->id,
                'title' => $lesson->title,
                'course' => $course?->title ?? 'General Course',
                'file' => $relativeAttachmentPath,
            ];
        }

        return [
            'generated_count' => count($generated),
            'skipped_count' => count($skipped),
            'generated' => $generated,
        ];
    }

    /**
     * Render HTML string directly into PDF file on disk after sanitizing non-ASCII/Devanagari characters.
     */
    private function renderPdfToFile(string $html, string $outputPath): void
    {
        $cleanHtml = $this->sanitizeForDompdf($html);

        $options = new Options;
        $options->set('defaultFont', 'Helvetica');
        $options->set('isHtml5ParserEnabled', true);
        $options->set('isRemoteEnabled', false);

        $dompdf = new Dompdf($options);
        $dompdf->loadHtml($cleanHtml);
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();

        file_put_contents($outputPath, $dompdf->output());
    }

    /**
     * Sanitize HTML so that DomPDF's Latin fonts (Helvetica) never produce question marks (????).
     */
    private function sanitizeForDompdf(string $html): string
    {
        // 1. Remove parenthetical Nepali/Devanagari expressions like (पारदर्शिता)
        $html = preg_replace('/\s*\([\x{0900}-\x{097F}\s\/\-,.:;]+\)/u', '', $html);

        // 2. Remove any remaining standalone Devanagari glyphs
        $html = preg_replace('/[\x{0900}-\x{097F}]+/u', '', $html);

        // 3. Clean up empty parentheses
        $html = preg_replace('/\(\s*\)/', '', $html);

        // 4. Normalize double spaces before punctuation
        $html = preg_replace('/\s+([,.;:?!])/', '$1', $html);
        $html = preg_replace('/,\s*,/', ',', $html);

        return $html;
    }

    /**
     * Build rich, 100% pure theoretical study notes on a crisp white background.
     * Contains NO quiz questions, NO MCQs, NO options A/B/C/D, and NO Devanagari question marks.
     */
    public function buildPureTheoreticalHtml(Lesson $lesson, ?Course $course, $module): string
    {
        $courseTitle = htmlspecialchars($course?->title ?? 'Loksewa Aayog Preparation Curriculum', ENT_QUOTES, 'UTF-8');
        $moduleTitle = htmlspecialchars($module?->title ?? 'Core Curriculum Module', ENT_QUOTES, 'UTF-8');
        $lessonTitle = htmlspecialchars($lesson->title, ENT_QUOTES, 'UTF-8');
        $duration = (int) ($lesson->duration_minutes ?: 45);

        // Format pure theoretical content
        $theoryContentHtml = $this->formatPureTheoreticalContent($lesson, $course, $module);

        return <<<HTML
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{$lessonTitle} - Theoretical Study Notes</title>
    <style>
        @page {
            margin: 34px 34px 34px 34px;
            background: #ffffff;
        }
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            font-size: 8.8pt;
            line-height: 1.46;
            color: #1e293b;
            background: #ffffff;
            margin: 0;
            padding: 0;
        }
        .header-box {
            border-bottom: 2.5px solid #059669;
            padding-bottom: 8px;
            margin-bottom: 12px;
        }
        .top-meta {
            font-size: 7.5pt;
            text-transform: uppercase;
            letter-spacing: 0.8px;
            color: #059669;
            font-weight: bold;
            margin-bottom: 2px;
        }
        .course-title {
            font-size: 8.2pt;
            color: #64748b;
            font-weight: bold;
            margin-bottom: 3px;
        }
        .lesson-title {
            font-size: 14pt;
            font-weight: bold;
            color: #0f172a;
            margin: 0 0 5px 0;
            line-height: 1.25;
        }
        .badge-row {
            margin-top: 4px;
        }
        .badge {
            display: inline-block;
            background-color: #f1f5f9;
            color: #334155;
            font-size: 6.8pt;
            font-weight: bold;
            padding: 2px 6px;
            border-radius: 4px;
            border: 1px solid #cbd5e1;
            margin-right: 4px;
        }
        .badge-emerald {
            background-color: #ecfdf5;
            color: #065f46;
            border-color: #a7f3d0;
        }
        .badge-blue {
            background-color: #eff6ff;
            color: #1e40af;
            border-color: #bfdbfe;
        }
        .badge-amber {
            background-color: #fffbeb;
            color: #92400e;
            border-color: #fde68a;
        }
        
        .section-heading {
            font-size: 10pt;
            font-weight: bold;
            color: #065f46;
            border-bottom: 1px solid #cbd5e1;
            padding-bottom: 3px;
            margin-top: 13px;
            margin-bottom: 6px;
            text-transform: uppercase;
            letter-spacing: 0.4px;
        }
        .sub-heading {
            font-size: 9pt;
            font-weight: bold;
            color: #0f172a;
            margin-top: 8px;
            margin-bottom: 3px;
        }
        .callout-box {
            background-color: #f8fafc;
            border-left: 3.5px solid #059669;
            border-top: 1px solid #e2e8f0;
            border-right: 1px solid #e2e8f0;
            border-bottom: 1px solid #e2e8f0;
            padding: 8px 10px;
            margin: 8px 0;
            border-radius: 0 4px 4px 0;
        }
        .callout-title {
            font-weight: bold;
            font-size: 8.2pt;
            color: #065f46;
            margin-bottom: 3px;
            text-transform: uppercase;
            letter-spacing: 0.3px;
        }
        p {
            margin: 0 0 6px 0;
            text-align: justify;
        }
        ul, ol {
            margin: 0 0 8px 0;
            padding-left: 18px;
        }
        li {
            margin-bottom: 3px;
        }
        .info-table {
            width: 100%;
            border-collapse: collapse;
            margin: 8px 0;
            font-size: 7.8pt;
        }
        .info-table th {
            background-color: #f1f5f9;
            color: #1e293b;
            font-weight: bold;
            text-align: left;
            padding: 5px 7px;
            border: 1px solid #cbd5e1;
        }
        .info-table td {
            padding: 4px 7px;
            border: 1px solid #e2e8f0;
            vertical-align: top;
        }
        .info-table tr:nth-child(even) td {
            background-color: #f8fafc;
        }
        .footer {
            margin-top: 18px;
            border-top: 1px solid #cbd5e1;
            padding-top: 5px;
            font-size: 6.8pt;
            color: #94a3b8;
            text-align: center;
        }
    </style>
</head>
<body>

    <!-- Header Section -->
    <div class="header-box">
        <div class="top-meta">Public Service Commission (Loksewa Aayog) &bull; Theoretical Study Resource</div>
        <div class="course-title">{$courseTitle} &raquo; {$moduleTitle}</div>
        <h1 class="lesson-title">{$lessonTitle}</h1>
        <div class="badge-row">
            <span class="badge badge-emerald">Comprehensive Theory Module</span>
            <span class="badge badge-blue">Duration: {$duration} Mins</span>
            <span class="badge badge-amber">Official Syllabus Prescribed</span>
        </div>
    </div>

    <!-- Core Theoretical Content -->
    <div class="content-body">
        {$theoryContentHtml}
    </div>

    <!-- Examination Writing Pointers Box -->
    <div class="callout-box">
        <div class="callout-title">&#9997; Loksewa Subjective Writing Guidelines &amp; Analytical Framework</div>
        <p style="margin-bottom: 3px;">When answering subjective theoretical questions related to this unit in the examination:</p>
        <ul style="margin-bottom: 0;">
            <li><strong>Structured Presentation:</strong> Open with a precise conceptual definition, enumerate constitutional/statutory provisions, analyze core operational dimensions, outline current institutional challenges in Nepal, and conclude with actionable reform measures.</li>
            <li><strong>Authoritative Citations:</strong> Cite relevant statutory Acts, Bylaws, Articles of the Constitution of Nepal, and Periodic Plan targets.</li>
            <li><strong>Good Governance Impact:</strong> Emphasize transparency, accountability, rule of law, and public service delivery excellence.</li>
        </ul>
    </div>

    <!-- Footer -->
    <div class="footer">
        Loksewa Path LMS &bull; Comprehensive Theoretical Study Series &bull; Pure Academic Reference
    </div>

</body>
</html>
HTML;
    }

    /**
     * Format pure theoretical content, ensuring zero quiz/JSON leakage and enriching short topics with full explanations.
     */
    private function formatPureTheoreticalContent(Lesson $lesson, ?Course $course, $module): string
    {
        $raw = trim($lesson->content ?? '');

        // If content is a JSON string (e.g. from quiz lessons), synthesize topic theory
        $isJson = (str_starts_with($raw, '[') && str_ends_with($raw, ']')) || (str_starts_with($raw, '{') && str_ends_with($raw, '}'));

        // If lesson has genuine extensive theoretical content (e.g. > 300 chars of text/markdown and not JSON)
        if (! empty($raw) && ! $isJson && strlen($raw) > 300) {
            $formatted = $this->convertMarkdownToHtml($raw);

            return <<<HTML
            <div class="section-heading">1. Detailed Syllabus Theory &amp; Subject Matter</div>
            <div class="lesson-text">
                {$formatted}
            </div>
HTML;
        }

        // Generate tailored, deeply explained subject theory for the specific topic
        return $this->generateTailoredTheoryExplanation($lesson, $course, $module);
    }

    /**
     * Generate in-depth, rich, subject-matter specific theoretical notes for individual topics.
     */
    private function generateTailoredTheoryExplanation(Lesson $lesson, ?Course $course, $module): string
    {
        $title = $lesson->title;
        $tLower = strtolower($title);

        // 1. Demand Elasticity & Market Equilibrium (NRB Economics)
        if (str_contains($tLower, 'demand elasticity') || str_contains($tLower, 'market equilibrium')) {
            return <<<'HTML'
            <div class="section-heading">1. Theoretical Foundation of Demand Elasticity</div>
            <p><strong>Elasticity of Demand</strong> measures the degree of responsiveness of quantity demanded of a commodity to a change in one of its determinants (price, income, or price of related goods).</p>
            <ul>
                <li><strong>Price Elasticity of Demand (Ep):</strong> Percentage change in quantity demanded divided by percentage change in price. Degrees include:
                    <ol>
                        <li><em>Perfectly Inelastic (Ep = 0):</em> Quantity remains constant regardless of price (e.g., life-saving medicines).</li>
                        <li><em>Inelastic (0 < Ep < 1):</em> Change in quantity is less than change in price (e.g., essential food grains, salt).</li>
                        <li><em>Unitary Elastic (Ep = 1):</em> Proportional change in quantity equals change in price (Rectangular hyperbola).</li>
                        <li><em>Elastic (Ep > 1):</em> Significant change in demand for minor price changes (e.g., luxury consumer goods).</li>
                        <li><em>Perfectly Elastic (Ep = Infinity):</em> Infinite demand at given price, zero demand above it.</li>
                    </ol>
                </li>
                <li><strong>Income Elasticity of Demand (Ey):</strong> Classifies goods into Normal (Ey > 0), Inferior (Ey < 0), and Luxury (Ey > 1).</li>
                <li><strong>Cross Elasticity of Demand (Exy):</strong> Positive for Substitutes (Tea and Coffee), Negative for Complements (Car and Petrol).</li>
            </ul>

            <div class="section-heading">2. Market Equilibrium &amp; Pricing Determination</div>
            <p><strong>Market Equilibrium</strong> occurs at the price level where Market Demand exactly equals Market Supply. At this intersection point, there is neither surplus nor shortage.</p>
            <table class="info-table">
                <thead>
                    <tr>
                        <th style="width: 25%;">Market Situation</th>
                        <th style="width: 45%;">Mechanics &amp; Dynamics</th>
                        <th style="width: 30%;">Price Adjustment</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><strong>Excess Supply (Supply > Demand)</strong></td>
                        <td>Market price is above equilibrium; unsold inventory accumulates.</td>
                        <td>Downward pressure on price until equilibrium is restored.</td>
                    </tr>
                    <tr>
                        <td><strong>Market Equilibrium (Supply = Demand)</strong></td>
                        <td>Optimal resource allocation; market clears with zero deadweight loss.</td>
                        <td>Stable equilibrium price and quantity.</td>
                    </tr>
                    <tr>
                        <td><strong>Excess Demand (Demand > Supply)</strong></td>
                        <td>Market price is below equilibrium; buyers bid up prices for scarce goods.</td>
                        <td>Upward pressure on price until equilibrium is reached.</td>
                    </tr>
                </tbody>
            </table>

            <div class="section-heading">3. Central Banking &amp; Policy Implications in Nepal</div>
            <p>In central banking and public finance in Nepal, price elasticity determines the tax incidence of excise duties, the transmission of monetary policy interest rate adjustments to consumer demand, and foreign trade volume changes under exchange rate variations.</p>
HTML;
        }

        // 2. NRB Act 2058 & BAFIA 2073 Governance
        if (str_contains($tLower, 'nrb act') || str_contains($tLower, 'bafia')) {
            return <<<'HTML'
            <div class="section-heading">1. Statutory Architecture of Nepal Rastra Bank Act, 2058 (2002)</div>
            <p><strong>Nepal Rastra Bank Act, 2058</strong> establishes NRB as an autonomous, corporate central banking institution with perpetual succession. Its statutory objectives under Section 4 include:</p>
            <ul>
                <li>Maintaining price stability and balance of payments stability to support sustainable economic growth.</li>
                <li>Ensuring financial sector stability, liquidity, and public trust in the banking system.</li>
                <li>Developing and regulating a secure, healthy, and efficient national payments and settlement system.</li>
            </ul>

            <div class="sub-heading">Corporate Governance Framework of NRB</div>
            <ul>
                <li><strong>Board of Directors:</strong> Composed of 7 members: Governor (Chairperson), Secretary of Ministry of Finance, Two Deputy Governors, and Three eminent non-executive directors appointed by Government of Nepal.</li>
                <li><strong>Appointment &amp; Tenure:</strong> Governor is appointed by the Government of Nepal upon recommendation of a 3-member committee headed by the Minister of Finance. Tenure is 5 years with statutory protection from arbitrary removal.</li>
            </ul>

            <div class="section-heading">2. Bank and Financial Institutions Act, 2073 (BAFIA)</div>
            <p><strong>BAFIA 2073</strong> provides the unified legal regime for licensing, regulating, and supervising Commercial Banks (Class 'A'), Development Banks (Class 'B'), Finance Companies (Class 'C'), and Microfinance Institutions (Class 'D').</p>
            <table class="info-table">
                <thead>
                    <tr>
                        <th style="width: 25%;">Core Area</th>
                        <th style="width: 45%;">Statutory Provisions under BAFIA 2073</th>
                        <th style="width: 30%;">Governance Significance</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><strong>Board Composition</strong></td>
                        <td>Minimum 5 and maximum 7 directors; mandatory inclusion of at least 1 independent director with proven professional qualifications.</td>
                        <td>Prevents promoter hegemony and conflict of interest.</td>
                    </tr>
                    <tr>
                        <td><strong>Credit Exposure Limits</strong></td>
                        <td>Single Borrower Limit (SBL), restrictions on insider lending to promoters, directors, and their family associates.</td>
                        <td>Mitigates systemic credit concentration risk.</td>
                    </tr>
                    <tr>
                        <td><strong>Capital Adequacy</strong></td>
                        <td>Strict adherence to Basel III framework, minimum Core Capital (Tier 1) and Total Capital Adequacy Ratio (CAR).</td>
                        <td>Buffers financial institutions against unforeseen credit shocks.</td>
                    </tr>
                </tbody>
            </table>
HTML;
        }

        // 3. Monetary Policy, Central Banking & Money Supply
        if (str_contains($tLower, 'monetary policy') || str_contains($tLower, 'money supply')) {
            return <<<'HTML'
            <div class="section-heading">1. Concepts &amp; Aggregates of Money Supply</div>
            <p><strong>Money Supply</strong> represents the total volume of monetary assets available in the economy at a specific point in time. NRB categorizes money supply into standard aggregates:</p>
            <ul>
                <li><strong>Reserve Money (M0 / High-Powered Money):</strong> Currency in circulation outside NRB + Deposits of BFIs with NRB + Other deposits with NRB.</li>
                <li><strong>Narrow Money (M1):</strong> Currency held by the public + Demand deposits (current accounts) with commercial banks. Highly liquid transaction money.</li>
                <li><strong>Broad Money (M2):</strong> M1 + Time deposits (fixed deposits, savings deposits) with BFIs. Primary operational intermediate target in Nepal.</li>
            </ul>

            <div class="section-heading">2. Monetary Policy Instruments in Nepal</div>
            <table class="info-table">
                <thead>
                    <tr>
                        <th style="width: 25%;">Instrument</th>
                        <th style="width: 45%;">Operational Mechanism</th>
                        <th style="width: 30%;">Macroeconomic Objective</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><strong>Cash Reserve Ratio (CRR)</strong></td>
                        <td>Statutory minimum percentage of total deposit liabilities that commercial banks must maintain as liquid cash balance with NRB (typically 4%).</td>
                        <td>Direct control over banking credit creation capacity.</td>
                    </tr>
                    <tr>
                        <td><strong>Statutory Liquidity Ratio (SLR)</strong></td>
                        <td>Prescribed percentage of deposits held in cash, gold, and approved government securities.</td>
                        <td>Ensures solvency and liquidity protection for depositors.</td>
                    </tr>
                    <tr>
                        <td><strong>Interest Rate Corridor (IRC)</strong></td>
                        <td>Standing Liquidity Facility (SLF rate - ceiling), Policy/Repo rate (target), and Standing Deposit Facility (SDF rate - floor).</td>
                        <td>Stabilizes short-term interbank interest rate volatility.</td>
                    </tr>
                    <tr>
                        <td><strong>Open Market Operations (OMO)</strong></td>
                        <td>Outright Purchase/Sale of Treasury Bills, Repo, and Reverse Repo auctions.</td>
                        <td>Fine-tunes daily liquidity surplus or deficit in banking system.</td>
                    </tr>
                </tbody>
            </table>
HTML;
        }

        // 4. Balance of Payments & Forex Management
        if (str_contains($tLower, 'balance of payments') || str_contains($tLower, 'forex') || str_contains($tLower, 'exchange rate')) {
            return <<<'HTML'
            <div class="section-heading">1. Structure of Balance of Payments</div>
            <p>The <strong>Balance of Payments (BoP)</strong> is a systematic statistical record of all economic transactions between the residents of Nepal and the rest of the world during a given financial year.</p>
            <ul>
                <li><strong>Current Account:</strong> Records Trade in Goods (Merchandise Export/Import), Services (Tourism, IT, Education), Primary Income (Investment yield, compensation), and Secondary Income (Workers' Remittances - major driver in Nepal).</li>
                <li><strong>Capital Account:</strong> Capital transfers (disaster grants, debt forgiveness) and acquisition/disposal of non-produced non-financial assets.</li>
                <li><strong>Financial Account:</strong> Foreign Direct Investment (FDI), Foreign Portfolio Investment (FPI), Official Development Assistance (ODA loans), and Commercial borrowings.</li>
                <li><strong>Overall Balance &amp; Reserves:</strong> Net BoP position determining the accumulation or drawdown of Gross Foreign Exchange Reserves.</li>
            </ul>

            <div class="section-heading">2. Foreign Exchange Regime of Nepal</div>
            <table class="info-table">
                <thead>
                    <tr>
                        <th style="width: 25%;">Forex Dimension</th>
                        <th style="width: 45%;">Institutional &amp; Operating Framework</th>
                        <th style="width: 30%;">Economic Significance</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><strong>Pegged Exchange Rate</strong></td>
                        <td>Nepalese Rupee (NPR) is pegged to Indian Rupee (INR) at fixed rate of 100 INR = 160 NPR since 1993.</td>
                        <td>Provides macroeconomic price anchor and eliminates trade volatility with Nepal's largest trading partner.</td>
                    </tr>
                    <tr>
                        <td><strong>Convertible Currencies</strong></td>
                        <td>Floating exchange rate against US Dollar (USD), Euro (EUR), GBP, based on cross-currency rates with USD/INR in international forex markets.</td>
                        <td>Reflects international market liquidity and import settlement costs.</td>
                    </tr>
                    <tr>
                        <td><strong>Reserves Adequacy</strong></td>
                        <td>Targeted reserve buffer to cover minimum 7 months of merchandise and service imports under NRB monetary policy guidelines.</td>
                        <td>Sovereign external creditworthiness and import safety net.</td>
                    </tr>
                </tbody>
            </table>
HTML;
        }

        // 5. Computer & MS Office
        if (str_contains($tLower, 'ms word') || str_contains($tLower, 'excel') || str_contains($tLower, 'computer fundamentals')) {
            return <<<'HTML'
            <div class="section-heading">1. MS Word &amp; Official Document Processing</div>
            <p><strong>Word Processing in Civil Service:</strong> In administrative offices, MS Word is utilized for drafting official letters, cabinet memos, policy briefs, circulars, and notices according to official Nepali formatting standards.</p>
            <ul>
                <li><strong>Formatting &amp; Layout:</strong> Margins (Standard 1 inch), Header/Footer, Page Numbering, Multi-level numbering for legal clauses, Table of Contents generation.</li>
                <li><strong>Mail Merge:</strong> Automated feature used for mass official communications, examination admit cards, and transfer notices by linking Word template with Excel database.</li>
                <li><strong>Document Security:</strong> Track Changes, Commenting, Password Protection, Digital Signature, and PDF conversion.</li>
            </ul>

            <div class="section-heading">2. MS Excel &amp; Financial Analysis</div>
            <p><strong>Spreadsheet Applications:</strong> Excel provides analytical and computational capabilities for budgeting, payroll, tax calculations, store inventory records, and administrative statistics.</p>
            <table class="info-table">
                <thead>
                    <tr>
                        <th style="width: 25%;">Function Category</th>
                        <th style="width: 45%;">Key Functions &amp; Syntax</th>
                        <th style="width: 30%;">Administrative Use</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><strong>Mathematical &amp; Statistical</strong></td>
                        <td><code>SUM()</code>, <code>AVERAGE()</code>, <code>COUNTIF()</code>, <code>SUMIF()</code>, <code>ROUND()</code></td>
                        <td>Payroll totals, departmental expenditure aggregation, marks tabulation.</td>
                    </tr>
                    <tr>
                        <td><strong>Logical &amp; Conditional</strong></td>
                        <td><code>IF()</code>, <code>AND()</code>, <code>OR()</code>, <code>IFS()</code>, <code>IFERROR()</code></td>
                        <td>Grade allocation, tax slab calculation, compliance checks.</td>
                    </tr>
                    <tr>
                        <td><strong>Lookup &amp; Reference</strong></td>
                        <td><code>VLOOKUP()</code>, <code>XLOOKUP()</code>, <code>INDEX()</code>, <code>MATCH()</code></td>
                        <td>Matching employee codes with salary scales, inventory retrieval.</td>
                    </tr>
                    <tr>
                        <td><strong>Data Analysis</strong></td>
                        <td>Pivot Tables, Data Filtering, Conditional Formatting, Goal Seek</td>
                        <td>Multi-dimensional financial summaries and budget reporting.</td>
                    </tr>
                </tbody>
            </table>
HTML;
        }

        // 6. Telecom & Networking
        if (str_contains($tLower, 'cellular') || str_contains($tLower, 'optical networks') || str_contains($tLower, 'ip routing') || str_contains($tLower, 'telecommunications act')) {
            return <<<'HTML'
            <div class="section-heading">1. Cellular Mobile Systems &amp; Next-Gen Architecture</div>
            <p><strong>Cellular Architecture:</strong> Cellular technology divides coverage regions into geographic 'cells', each served by a Base Station (eNodeB in 4G, gNodeB in 5G), enabling frequency reuse and seamless handover.</p>
            <ul>
                <li><strong>Evolutionary Milestones:</strong> 2G (GSM - Voice/SMS), 3G (UMTS - Mobile Internet), 4G (LTE - All-IP Broadband), 5G (NR - Ultra-low latency, massive IoT, beamforming, network slicing).</li>
                <li><strong>Core Network Components:</strong> User Equipment (UE), Radio Access Network (RAN), Mobility Management Entity (MME), Serving Gateway (S-GW), Packet Data Network Gateway (P-GW), Home Subscriber Server (HSS).</li>
            </ul>

            <div class="section-heading">2. Optical Fiber &amp; Network Infrastructure</div>
            <p><strong>Optical Communication:</strong> Transmits data as light pulses through silica glass fibers based on the principle of <em>Total Internal Reflection (TIR)</em>.</p>
            <table class="info-table">
                <thead>
                    <tr>
                        <th style="width: 25%;">Technology</th>
                        <th style="width: 45%;">Architecture &amp; Specifications</th>
                        <th style="width: 30%;">Application in Nepal</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><strong>Optical Fiber Cable (OFC)</strong></td>
                        <td>Single-Mode Fiber (SMF - 9/125 um) for long-haul transmission; Multi-Mode Fiber (MMF - 50/125 um) for local networks.</td>
                        <td>National Information Highway along Mid-Hill &amp; East-West Corridors.</td>
                    </tr>
                    <tr>
                        <td><strong>DWDM &amp; GPON</strong></td>
                        <td>Dense Wavelength Division Multiplexing (multi-wavelength Terabit backbone) and Gigabit Passive Optical Networks (FTTH).</td>
                        <td>High-speed residential broadband and inter-district transmission.</td>
                    </tr>
                    <tr>
                        <td><strong>IP Routing &amp; Security</strong></td>
                        <td>OSPF, BGP, MPLS VPNs, IPv4/IPv6 dual-stack, Next-Gen Firewalls, DDoS Mitigation.</td>
                        <td>Data center security, enterprise connectivity, and telecom core reliability.</td>
                    </tr>
                </tbody>
            </table>

            <div class="section-heading">3. Regulatory Framework: Telecommunications Act, 2053</div>
            <p>The <strong>Telecommunications Act, 2053 (1997)</strong> establishes the <em>Nepal Telecommunications Authority (NTA)</em> as the autonomous regulator responsible for licensing, frequency spectrum management, tariff regulation, quality of service enforcement, and Rural Telecommunications Development Fund (RTDF) administration.</p>
HTML;
        }

        // 7. Generic / Assessment Theoretical Synthesis for NEA & General Modules
        return $this->generateThematicAssessmentTheory($lesson, $module);
    }

    /**
     * Provide comprehensive thematic theoretical review for assessment and general syllabus units.
     */
    private function generateThematicAssessmentTheory(Lesson $lesson, $module): string
    {
        $title = htmlspecialchars($lesson->title, ENT_QUOTES, 'UTF-8');
        $moduleTitle = htmlspecialchars($module?->title ?? 'Core Curriculum Module', ENT_QUOTES, 'UTF-8');

        return <<<HTML
        <div class="section-heading">1. Detailed Syllabus Theory &amp; Conceptual Framework</div>
        <p><strong>{$title}</strong> constitutes an essential curriculum unit within <em>{$moduleTitle}</em> under the prescribed guidelines of the Public Service Commission (Loksewa Aayog). Examination candidates must master both theoretical concepts and their statutory applications in Nepal.</p>

        <div class="sub-heading">Core Theoretical Foundations &amp; Administrative Principles</div>
        <ul>
            <li><strong>Doctrinal Scope:</strong> Standard definitions, operational significance, and structural position within Nepal's public governance and corporate administrative architecture.</li>
            <li><strong>Legislative &amp; Regulatory Mandates:</strong> Prevailing statutory Acts, Bylaws, Government Directives, and constitutional provisions governing {$title}.</li>
            <li><strong>Procedural Standards:</strong> Standard operational guidelines (SOPs), documentation hierarchy, verification steps, and internal accountability controls.</li>
            <li><strong>Practical Public Sector Application:</strong> Enhancing service quality, ensuring cost efficiency, preventing procedural redundancies, and enforcing institutional transparency.</li>
        </ul>

        <div class="section-heading">2. Comprehensive Analytical &amp; Operational Matrix</div>
        <table class="info-table">
            <thead>
                <tr>
                    <th style="width: 25%;">Curriculum Pillar</th>
                    <th style="width: 45%;">Theoretical &amp; Legal Framework</th>
                    <th style="width: 30%;">PSC Examination Focus</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><strong>Concept &amp; Principles</strong></td>
                    <td>Fundamental axioms, evolutionary background, and standard institutional definitions.</td>
                    <td>Conceptual clarity and definition precision.</td>
                </tr>
                <tr>
                    <td><strong>Statutory Rules</strong></td>
                    <td>Applicable legal clauses, institutional jurisdictions, and prescribed official timelines.</td>
                    <td>Accurate legal terminology and citation.</td>
                </tr>
                <tr>
                    <td><strong>Operational Workflows</strong></td>
                    <td>Step-by-step procedures, documentation, authorization matrices, and filing protocols.</td>
                    <td>Procedural accuracy in subjective answers.</td>
                </tr>
                <tr>
                    <td><strong>Contemporary Issues</strong></td>
                    <td>Digital transition, institutional bottlenecks, integrity safeguards, and reform priorities.</td>
                    <td>Analytical problem-solving and recommendations.</td>
                </tr>
            </tbody>
        </table>

        <div class="section-heading">3. Challenges, Governance Safeguards &amp; Way Forward in Nepal</div>
        <p>In the public service and state enterprise landscape of Nepal, the effective execution of {$title} requires addressing critical administrative factors:</p>
        <ul>
            <li><strong>Institutional Modernization:</strong> Transitioning from legacy manual documentation to integrated digital governance platforms.</li>
            <li><strong>Human Resource Competency:</strong> Continuous professional training and strict adherence to organizational code of conduct.</li>
            <li><strong>Internal &amp; External Oversight:</strong> Enhancing internal audit efficacy, management inspections, and compliance with statutory oversight bodies.</li>
        </ul>
HTML;
    }

    /**
     * Convert markdown headers, lists, and bold text to clean HTML.
     */
    private function convertMarkdownToHtml(string $markdown): string
    {
        if (str_contains($markdown, '<p>') || str_contains($markdown, '<div>') || str_contains($markdown, '<h3>')) {
            return $markdown;
        }

        $lines = explode("\n", $markdown);
        $html = '';
        $inList = false;

        foreach ($lines as $line) {
            $trimmed = trim($line);

            if (empty($trimmed)) {
                if ($inList) {
                    $html .= "</ul>\n";
                    $inList = false;
                }
                continue;
            }

            if (str_starts_with($trimmed, '### ')) {
                if ($inList) {
                    $html .= "</ul>\n";
                    $inList = false;
                }
                $title = htmlspecialchars(substr($trimmed, 4), ENT_QUOTES, 'UTF-8');
                $html .= "<div class=\"sub-heading\">{$title}</div>\n";
            } elseif (str_starts_with($trimmed, '## ')) {
                if ($inList) {
                    $html .= "</ul>\n";
                    $inList = false;
                }
                $title = htmlspecialchars(substr($trimmed, 3), ENT_QUOTES, 'UTF-8');
                $html .= "<div class=\"section-heading\">{$title}</div>\n";
            } elseif (str_starts_with($trimmed, '# ')) {
                if ($inList) {
                    $html .= "</ul>\n";
                    $inList = false;
                }
                $title = htmlspecialchars(substr($trimmed, 2), ENT_QUOTES, 'UTF-8');
                $html .= "<div class=\"section-heading\">{$title}</div>\n";
            } elseif (str_starts_with($trimmed, '- ') || str_starts_with($trimmed, '* ')) {
                if (! $inList) {
                    $html .= "<ul>\n";
                    $inList = true;
                }
                $itemText = substr($trimmed, 2);
                $itemText = $this->formatInlineMarkdown($itemText);
                $html .= "<li>{$itemText}</li>\n";
            } elseif (preg_match('/^\d+\.\s+(.*)$/', $trimmed, $matches)) {
                if ($inList) {
                    $html .= "</ul>\n";
                    $inList = false;
                }
                $itemText = $this->formatInlineMarkdown($matches[1]);
                $html .= "<p><strong>&bull;</strong> {$itemText}</p>\n";
            } else {
                if ($inList) {
                    $html .= "</ul>\n";
                    $inList = false;
                }
                $pText = $this->formatInlineMarkdown($trimmed);
                $html .= "<p>{$pText}</p>\n";
            }
        }

        if ($inList) {
            $html .= "</ul>\n";
        }

        return $html;
    }

    private function formatInlineMarkdown(string $text): string
    {
        $text = preg_replace('/\*\*(.*?)\*\*/', '<strong>$1</strong>', $text);
        $text = preg_replace('/\*([^\*]+)\*/', '<em>$1</em>', $text);
        $text = preg_replace('/`([^`]+)`/', '<code style="background:#f1f5f9;padding:1px 4px;border-radius:3px;font-size:8pt;">$1</code>', $text);

        return $text;
    }
}
